### ISSUE TITLE
SolrConnection.PostStream with SendChunk

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#101]
(moved from https://code.google.com/p/solrnet/issues/detail?id=170 )

The current SolrConnection.PostStream method accepts a stream which must support the Length property.

It would be nice that, if Length raises a NotSupportedException, the stream was sent with SendChunk option enabled, thus allowing stream whose size is not known a priori.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
