### ISSUE TITLE
Unify core configuration

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#102]
(moved from https://code.google.com/p/solrnet/issues/detail?id=173 )

Currently each IoC integration has its own way to define cores. Create a centralized, 
unified model that makes IoC configuration more uniform.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
