### ISSUE TITLE
mm (minimum should match) expressions

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#103]
(moved from https://code.google.com/p/solrnet/issues/detail?id=179 )

Just as in https://github.com/mausch/SolrNet/issues/79, mm expressions currently have to be written as strings. Model mm expressions to avoid stringly-typed programming.

References:
- http://wiki.apache.org/solr/DisMaxQParserPlugin#mm_.28Minimum_.27Should.27_Match.29
- http://lucene.apache.org/solr/4_4_0/solr-core/org/apache/solr/util/doc-files/min-should-match.html

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
