### ISSUE TITLE
Highlighting boundary scanner

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#104]
(moved from https://code.google.com/p/solrnet/issues/detail?id=188 )
http://wiki.apache.org/solr/HighlightingParameters/#hl.boundaryScanner

Since this only makes sense for FastVectorHighlighter, it has to be developed with https://github.com/mausch/SolrNet/issues/95 or after that.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
