### ISSUE TITLE
F# type provider

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#105]
(moved from https://code.google.com/p/solrnet/issues/detail?id=190 )

Ideas to implement F# type providers around Solr:
1. A type provider would infer the SolrNet document type from the Solr schema. From there SolrNet could pick up the inferred type and be used to do serialization/queries as usual. There could be two "modes", inferring two separate document types:
   - one for querying, which would include all stored fields
   - another one for indexing, which would include all non-copied fields.
2. Another type provider would infer types modeling a strongly-typed query DSL. Each field type would produce a different query type. This would produce a much better query API than a LINQ provider.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
