### ISSUE TITLE
DebuggerDisplayAttribute for queries

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#106]
(moved from https://code.google.com/p/solrnet/issues/detail?id=195 )

Define appropriate DebuggerDisplayAttribute in all query classes to make debugging easier.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
