### ISSUE TITLE
Shard info

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#107]
(moved from https://code.google.com/p/solrnet/issues/detail?id=197 )

Support `shards.info` / `shards.tolerant` in parameters and parse its response.

Reference:
- http://wiki.apache.org/solr/DistributedSearch#Distributed_Searching
- https://issues.apache.org/jira/browse/SOLR-3134

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
