### ISSUE TITLE
Atomic updates

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#108]
(moved from https://code.google.com/p/solrnet/issues/detail?id=199 )

References:
- http://wiki.apache.org/solr/Atomic_Updates
- http://yonik.com/solr/atomic-updates/
- http://dsahi.wordpress.com/2012/12/18/solr-atomic-update/
- http://wiki.apache.org/solr/UpdateXmlMessages#Optional_attributes_for_.22field.22

See also issue on the old issue tracker for ideas and discussion.

**Comment by rodrigopires** [comment]
Anything on this @mausch ? I'm looking for a way to make Atomic (partial) Updates using SolrNet...

I'm trying with "Add" method, mas it either a) duplicate the document (even with uniquekey), b) overwrite the document containing only the fields being updated...

Thanks!

**Comment by mausch** [comment]
@rodrigopires no news about this since that last update. You're welcome to continue working on it :)
That said, you should never get duplicate documents if you have a uniquekey, you might have something incorrectly configured in Solr. Ask on the mailing list.

**Comment by alanh-ti** [comment]
I've had a go at implementing atomic updates and just requested the changes are pulled into the master project.

https://github.com/mausch/SolrNet/pull/248

I hope others find this functionality useful.

**Comment by sowee15** [comment]
@alanh-ti @mausch It looks like there are checks failing in the pull request. Any idea when it will be fixed/merged? Thanks!

**Comment by xavier-morera** [comment]
I am taking care of this, the intent is this week.

**Comment by xavier-morera** [comment]
Currently work in progress in https://github.com/SolrNet/SolrNet/pull/339

**Comment by gjunge** [comment]
In Development branch now, will be part of the 1.0.0 release.
