### ISSUE TITLE
Realtime get

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#109]
(moved from https://code.google.com/p/solrnet/issues/detail?id=201 )

References:
- http://wiki.apache.org/solr/RealTimeGet
- http://solr.pl/en/2012/01/09/solr-4-0-realtime-get-2/

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
