### ISSUE TITLE
Multiple collations in spellcheck

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#110]
(moved from https://code.google.com/p/solrnet/issues/detail?id=211 )

SolrNet does not currently support multiple collations. SpellCheckResponseParser and SpellCheckResults should be modified to support this. 

To avoid multiple breaking changes, things should be changed to support extended results as well ( http://wiki.apache.org/solr/SpellCheckComponent#spellcheck.collateExtendedResults ).

New objects encapsulating this data should be immutable.

The patch/pull request must include tests for the cases of single collation, multiple simple collation, and multiple extended collations.

There was a pull request for this some time ago, but it lacked tests and objects were not immutable: https://github.com/mausch/SolrNet/pull/24 , still it could be used as reference.

**Comment by iandroutledge** [comment]
There's also another issue with a breaking change to do with collations in Solr 5.x.

See "6. The spellcheck response format has changed..." in "Upgrading from Solr 4.x" on http://lucene.apache.org/solr/5_0_0/changes/Changes.html.

I couldn't actually find anything about Solr 5 in SolrNet, so not sure if this should be raised as a separate issue or tackled as part of #110.

**Comment by mausch** [comment]
See https://github.com/mausch/SolrNet/pull/194

**Comment by xavier-morera** [comment]
Released 0.5.1
