### ISSUE TITLE
Schema API

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#111]
(moved from https://code.google.com/p/solrnet/issues/detail?id=214 )

Implement schema API operations.

Reference: http://wiki.apache.org/solr/SchemaRESTAPI

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
