### ISSUE TITLE
Problem with making request to Stats component with Date field

### ISSUE THREAD

**Issue by andreykorolev** [SolrNet/SolrNet#118]
Added field with type date to QueryOptions.Stats.FieldWithFacets and got:

```
Line 71:                 switch (name) {
Line 72:                     case "min":
Line 73:                        r.Min = Convert.ToDouble( statNode.Value, CultureInfo.InvariantCulture );
Line 74:                         break;
Line 75:                     case "max":
```

```
[FormatException: Input string was not in a correct format.]
   System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt) +542
   SolrNet.Impl.ResponseParsers.StatsResponseParser`1.ParseStatsNode(XElement node) in F:\_SolrNet\SolrNet\Impl\ResponseParsers\StatsResponseParser.cs:73
   SolrNet.Impl.ResponseParsers.StatsResponseParser`1.ParseStats(XElement node, String selector) in F:\_SolrNet\SolrNet\Impl\ResponseParsers\StatsResponseParser.cs:52
   SolrNet.Impl.ResponseParsers.StatsResponseParser`1.Parse(XDocument xml, SolrQueryResults`1 results) in F:\_SolrNet\SolrNet\Impl\ResponseParsers\StatsResponseParser.cs:38
   SolrNet.Utils.<>c__DisplayClass1`1.<ToFunc>b__0(T x) in F:\_SolrNet\SolrNet\Utils\Unit.cs:29
   SolrNet.Impl.ResponseParsers.AggregateResponseParser`1.Parse(XDocument xml, AbstractSolrQueryResults`1 results) in F:\_SolrNet\SolrNet\Impl\ResponseParsers\AggregateResponseParser.cs:15
   SolrNet.Impl.SolrQueryExecuter`1.Execute(ISolrQuery q, QueryOptions options) in F:\_SolrNet\SolrNet\Impl\SolrQueryExecuter.cs:589
```

**Comment by maislam** [comment]
Hello is there are any plan to implement this change? can not use date field for stats

**Comment by mausch** [comment]
@maislam Sure, what do you think about the model I last proposed here? Do you want to try and implement that?

**Comment by digitalpacman** [comment]
I would like to revive this. I am getting this exact error with a numerical field.  However I only have issues if the stats component generates all 0's.  

https://github.com/mausch/SolrNet/issues/205

It's the same error, but seems to be a different problem.

**Comment by mausch** [comment]
@digitalpacman  what do you think about the model I last proposed here? Do you want to try and implement that?

**Comment by digitalpacman** [comment]
@mausch Sorry this got lost in my inbox.  Do you mean you're asking me to submit a pull request?  This is an internal serialization problem.   I can download the source and recompile it with your changes and test it?  My issue was the serializer isn't handling the null formats, NaN's, etc.

**Comment by digitalpacman** [comment]
@mausch Current nuget package is still broken.

However, the current build of the source has it fixed.

**Comment by mausch** [comment]
@digitalpacman let's continue the discussion about your issue in #205 then.

**Comment by jernejg** [comment]
Hi @mausch !
Was there a reason your proposed model StatsResultTypedValues<T> was not implemented ?
Is there another way to get stats for date types?

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
