### ISSUE TITLE
StructureMap configuration does not support more than one core

### ISSUE THREAD

**Issue by mchadrdk** [SolrNet/SolrNet#167]
[The test](https://github.com/mausch/SolrNet/blob/master/StructureMap.SolrNetIntegration.Tests/StructureMapMultiCoreFixture.cs#L44) which checks for multi-core support does not return an error. But if you add in a call to StructureMap's verification method, it will throw several exceptions.

```
[Test]
public void Same_document_type_different_core_url()
{
    var core1 = ObjectFactory.Container.GetInstance<ISolrOperations<Entity2>>("entity2");
    var core2 = ObjectFactory.Container.GetInstance<ISolrOperations<Entity2>>("entity3");

    ObjectFactory.AssertConfigurationIsValid();
}
```

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
