### ISSUE TITLE
Nested documents a.k.a. Block Join

### ISSUE THREAD

**Issue by janhoy** [SolrNet/SolrNet#170]
Support indexing and searching nested documents. 

For indexing see https://cwiki.apache.org/confluence/display/solr/Uploading+Data+with+Index+Handlers?focusedCommentId=48792150#UploadingDatawithIndexHandlers-NestedChildDocuments

For querying the nested documents, see https://cwiki.apache.org/confluence/display/solr/Other+Parsers#OtherParsers-BlockJoinQueryParsers

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
