### ISSUE TITLE
ExtractResponse does not appear to be filling out the Metadata field

### ISSUE THREAD

**Issue by joshanderton** [SolrNet/SolrNet#173]
I have run a small test using SolrNet 4.0.2002 to perform an Extract on a document and it does not appear to be populating the Metadata field of the ExtractResponse. ExtractOnly is set to true and I have tried both the XML and Text ExtractFormats.  The metadata is in the XHTML returned but does not get parsed into the Metadata field.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
