### ISSUE TITLE
Clean up public interfaces ISolr*Operations

### ISSUE THREAD

**Issue by AlexeyKozhemiakin** [SolrNet/SolrNet#176]
At this point there is a (slight) mess in internal interfaces :
ISolrOperations, ISolrBasicOperations both are derived from ISolrReadOnlyOperation which is derived from ISolrBasicReadOnlyOperations

For example I have a an issuw with parametrized Commit method (with CommitOptions options) which exists only for ISolrBasicOperations, not for ISolrOperations. 

For sure we can fix just this use case, but probably worth reconsider - do we need so many - probably can simplify.

@mausch

**Comment by AlexeyKozhemiakin** [comment]
Thanks for pointing out to google-groups, i recalled I asked about that but failed to find where exactly.
I'll get back to this improvement shortly after more important ones.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
