### ISSUE TITLE
Trailing slash in solrUrl 

### ISSUE THREAD

**Issue by AlexeyKozhemiakin** [SolrNet/SolrNet#177]
I always forget in which format should I specify solrUrl in config, with or without trailing slash - localhost:8983/solr, or localhost:8983/solr/, so do my colleagues admins and devops. We have to trial&error run of app to identify what's right format.

I suggest add a tiny smart enhancement in SolrConnection that will take care of it.

Somewhere here (get & post methods)

``` csharp
public string Get(string relativeUrl, IEnumerable<KeyValuePair<string, string>> parameters) {
            var u = new UriBuilder(serverURL);
            u.Path += relativeUrl;
```

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
