### ISSUE TITLE
SolrCloud DataImportHandler Status

### ISSUE THREAD

**Issue by aniketkhare** [SolrNet/SolrNet#190]
Hi,

I already had written a Task scedular using c# to execute delta import and it is running properly on SolrCloud.
But wanted to check all the SolrCloud core DataImportHandler status for collection name Test (e.g Test_Shard1_Replica1, Test_Shard1_Replica2, Test_Shard2_Replica1, Test_Shard2_Replica1)
Do we have any method in SolrNet which will return the same.
Like http://localhost:8983/solr/Test_shard1_replica1/dataimport?command=status&wt=json

Thanks,
Aniket

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
