### ISSUE TITLE
ISolrBasicReadOnlyOperations.GetDIHStatus has non-nullable parameter

### ISSUE THREAD

**Issue by maritaria** [SolrNet/SolrNet#201]
``` C#
SolrDIHStatus GetDIHStatus(KeyValuePair<string, string> options);
```

Should probably have been

``` C#
SolrDIHStatus GetDIHStatus(IDictionary<string, string> options);
```

Because the parameter is plural. Also you cannot pass null to this method with the current signature.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
