### ISSUE TITLE
SolrDIHStatus doesn't support delta queries

### ISSUE THREAD

**Issue by maritaria** [SolrNet/SolrNet#202]
"statusMessages": {
    "Total Requests made to DataSource": "1",
    "Total Rows Fetched": "0",
    "Total Documents Processed": "0",
    "Total Documents Skipped": "0",
    "Delta Dump started": "2015-06-03 09:56:02",
    "Identifying Delta": "2015-06-03 09:56:02",
    "Deltas Obtained": "2015-06-03 09:56:02",
    "Building documents": "2015-06-03 09:56:02",
    "Total Changed Documents": "0",
    "Time taken": "0:0:0.475"
  }
The data class has fields specifically targeting full-import status messages.
The default/basic parser skips the fields
- Delta Dump started
- Identifying Delta
- Deltas Obtained
- Building documents

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
