### ISSUE TITLE
Containers - Add ability to pass Timeout to SolrConnection when container registers its services

### ISSUE THREAD

**Issue by stephenpope** [SolrNet/SolrNet#204]
While working on an issue with Unity I discovered that there was no easy way to set the timeout for the SolrConnection at initial registration, might be worth extending the signature (depending on implementation) to accept an optional time out as well as the URL.

**Comment by mausch** [comment]
Sure, go for it :+1:

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
