### ISSUE TITLE
Does SolrNet support dataimport handler?

### ISSUE THREAD

**Issue by louzhenyu** [SolrNet/SolrNet#207]
Dear all,
    I found SolrNet has a branch named as dataimport handler. Why it hasn't been integrated into the master branch? What is the best way to implement dih via SolrNet?

**Comment by serbrech** [comment]
Hi, I worked on that branch back when I needed this feature.
I think it wasn't merged because nobody else really needed it so far.

**Comment by mausch** [comment]
Indeed , @serbrech started working on it ( see https://github.com/mausch/SolrNet/pull/48 ), I continued but ran out of time/motivation. I don't use DIH personally.

To be honest it's been quite some time and I don't remember what was missing to merge it. It shouldn't be too hard to rebase it to the current master, then if you're interested figure out what's missing.

Let's continue this on #48 if you're interested.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
