### ISSUE TITLE
SolrNet produces bad query when string matching against Solr Keywords

### ISSUE THREAD

**Issue by digitalpacman** [SolrNet/SolrNet#212]
So if you put state codes into a property and need to query for "OR" and do `new SolrQueryByField("OriginGeographyKey", "OR")` then it ends up running `OriginGeographyKey:OR OR DestinationGeographyKey:OR`

Version 4 of Solr, this query will execute and give back bad results.  
Version 5 of Solr, this query fails saying bad syntax.

**Comment by mausch** [comment]
What would be the fix for this particular case? Does quoting work? Do parentheses work?

**Comment by digitalpacman** [comment]
@mausch Wrapping item in quotes works.  It should make sense that wrapping every single text comparison in quotes is the fix.

`SolrQueryByField("OriginGeographyKey", "OR")` should produce `OriginGeographyKey:"OR"`
`SolrQueryByField("OriginGeographyKey", "OR AND THAT")` should produce `OriginGeographyKey:"OR AND THAT"`
A range query should produce `OriginGeographyKey:["OR" TO "AND"]`

**Comment by xaviermorera** [comment]
That was a fast reply by Mauricio. I was gong to ask to turn on debugquery and use the analysis window to find out how if the StopFilter was affecting the query but oh well I got late to the party.

**Comment by mhov** [comment]
Not a stop word, OR & AND are protected keywords.  You could make them lower case if your field isn't case sensitive, or force quotes in the SolrQueryByField.

**Comment by xaviermorera** [comment]
Thanks for clarification

**Comment by digitalpacman** [comment]
Just so everyone knows I ran into this when upgrading. I upgraded our Solr server farm and then made them live, and then these exceptions flooded it.  We didn't catch it because we didn't test Oregon, state code OR.  So now I'm stuck spending resources on building word-escaping wrapped around SolrNet.  If it adds any weight to the cause.

**Comment by mhov** [comment]
Hey @mausch,  while one could go the route of automatic keyword escaping, I feel like that'll come back to haunt us or cause another edge case down the road.  Currently `SolrQueryByField.Quoted == true` only quotes when special escape characters are present, or not at all if False. I don't believe it can be forced on a string with no special characters.  What if changed `SolrQueryByField.Quoted` to `Nullable<bool>`.  False is no quotes, True is definite quotes, null is special character based like currently.

**Comment by mausch** [comment]
Yeah, [quoting everything is not desirable](http://stackoverflow.com/questions/19803472/strange-solr-query-with-double-quotes)... I've had that issue before.
I agree about setting this as a flag, however we need to think whether this is orthogonal to escaping special characters or not.
Also, does anyone know exactly what keywords are reserved in this context?

**Comment by mhov** [comment]
At least OR, NOT, AND (upper case only)

**Comment by digitalpacman** [comment]
So this issue is getting worse. The way SolrNet escapes special characters prevents me from fixing this problem.  If I do `new LocalParams { { "tag", "OriginGeographyKey" } } + new SolrQueryByField("OriginGeographyKey", "OR")` then I get an exception.  If I do `new LocalParams { { "tag", "OriginGeographyKey" } } + new SolrQueryByField("OriginGeographyKey", "\"OR\"")` then it escapes the quotes and I get no results.

Technically speaking, to get it right, I have to turn off SolrNet's special character escaping, and do all of the proper logic myself.

If you compare SolrNet to something like a SQL ORM, none of this is a problem in the ORM. It's expected behavior that the ORM is going to properly escape your queries based on the server product you're connecting to. SolrNet doesn't seem to have that same support for Solr.

**Comment by digitalpacman** [comment]
My current solution is:

public class WrappedQueryByField : SolrQueryByField
        {
            public WrappedQueryByField(string fieldName, string fieldValue)
                : base(fieldName, "\"" + fieldValue + "\"")
            {
                Quoted = false;
            }
        }

**Comment by digitalpacman** [comment]
I had posted a nice solution for my problem but had to delete it because SolrNet doesn't use IsAssignableFrom in it's type comparison for serialization.  Which means it doesn't support inheritance, so I'm just moving towards helper methods again.

**Comment by stanuku** [comment]
I had a similar issue yesterday. I'm developing a search feature in ASP.NET MVC and got stuck with the Oregon OR problem. I was using the SolrQueryInList query for checking my StateFiled to be in a list of states from a multi-select box on the UI. 
My solution to the problem was to add the bool Quote property on the SolrQueryInList, similar to the one available in SolrQueryByField. After adding that property and setting the Quote = false, if I supply OR as "\\OR"  or "OR*", I get the correct results.

I've forked and cloned the main branch locally. I'm just about done testing my fix and I've added a couple of Unit Tests around it. I'll be sending a pull request shortly.

Thanks
Sudarshan

**Comment by digitalpacman** [comment]
@stanuku This is the exact same approach I took. Quoted = false, and then quote it myself.  I don't understand why solrnet doesn't do this by default.  It's using the word "Quoted" to mean "Escaped". If you wrap your values in quotes, they're already all default escaped. "-" and "[" in a quoted string mean literally "-" and "[".

**Comment by stanuku** [comment]
'Quoted' is a bad choice for the Property name, it should've been named 'Escaped' or such.
and only SolrQueryByField has the ability currently.

**Comment by stanuku** [comment]
Seems like #185 was already created and has an open Pull request.

**Comment by mausch** [comment]
@stanuku #185 is specific for queries with a list of values (SolrQueryInList).

I agree about `Quoted` being kind of misleading now, but IIRC it started as a method that only applied quotes to query values as needed.

**Comment by stanuku** [comment]
@mausch: First of all, thank you for the wonderful library. Secondly, yes, my situation is similar to #185 and my local fix was exactly the same as the once stated in #185. Are you planning to merge that fix?

**Comment by zbrkic** [comment]
When updating to new version or changing source is not an option, you can create new self serialized query:

    public class SolrQueryByFieldEscaped : SolrQueryByField, ISelfSerializingQuery
    {
        public SolrQueryByFieldEscaped(string fieldName, string fieldValue) : base(fieldName, fieldValue)
        {
        }

        public string Query => Serialize();

        public string Serialize()
        {
            if (FieldName == null || FieldValue == null)
                return null;

            return $"{FieldName}:\\{Escape(FieldValue)}";
        }

        public string Escape(string value)
        {
            var r = Regex.Replace(value, "(\\+|\\-|\\&\\&|\\|\\||\\!|\\{|\\}|\\[|\\]|\\^|\\(|\\)|\\\"|\\~|\\:|\\;|\\\\)", "\\$1");

            if (r.IndexOf(' ') != -1)
                r = $"\"{r}\"";

            return r;
        }
    }

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
