### ISSUE TITLE
AbstractSolrQueryResults does not contain result start attribute

### ISSUE THREAD

**Issue by c-uhland** [SolrNet/SolrNet#237]
In the `ResultsResponseParser.Parse()` the NumFound is set for the `AbstractSolrQueryResults` but not the start information.
`<result name="response" numFound="103" start="30">`

This is important, because the https://cwiki.apache.org/confluence/display/solr/Pagination+of+Results  and the `StartOrCursor` implementation in SolrNet only works for queries with  _a sort containing a uniqueKey field tie breaker_.

The response in SolrNet does not contain any information about the start, although this was sent by Solr!

**Comment by thehudi** [comment]
Created Pull Request #239

**Comment by mausch** [comment]
Closing as we merged this years ago.
