### ISSUE TITLE
How to feed data to solr?

### ISSUE THREAD

**Issue by ZivHsu** [SolrNet/SolrNet#255]
this project can feed data to solr?
my solr version is 6.1
if yes how to use?

**Comment by xavier-morera** [comment]
@ZivHsu you can read in the documentation how to feed data in [CRUD operations](https://github.com/mausch/SolrNet/blob/master/Documentation/CRUD.md )


I also created a training called [Implementing Search in .NET Applications](https://www.pluralsight.com/courses/implementing-search-dotnet-applications) for Pluralsight that explains the process.

Good luck!

**Comment by ZivHsu** [comment]
I have no idea how to feed the data to designation field on myself,
And If i feed the docx file can i see the content on search result?
Just like search keyword on google "Solrnet" you will see the => Solr client for .Net. Contribute to "SolrNet" development by creating an account on GitHub.  on search result.
get content and highlight keyword
can i do it? how?

Thanks

**Comment by xavier-morera** [comment]
@ZivHsu you can read the documentation, watch the examples. Both are easy to do, very easy, but you need to review how it is done. For creating your own "documents" with your own fields, modify the schema. Feeding using the Extract() request handler you can index docx documents and it works.

**Comment by ZivHsu** [comment]
@xavier-morera  i can't see more in your Pluralsight, did you have another free path can give me see more?

I try to study [CRUD operations](https://github.com/mausch/SolrNet/blob/master/Documentation/CRUD.md), you meaning the feed it's uses HTTP request right?
so how can i select the collection?  like this ? "http://localhost:port/solr/#/collectionname" on URL ?

**Comment by ZivHsu** [comment]
@xavier-morera  I can connect to my solr now,
but i just no have idea on your code  SolrConnection.cs line 35 the version is mean solr version?

**Comment by xavier-morera** [comment]
There are several that are free. Here is one book I wrote that has always been free: https://www.syncfusion.com/resources/techportal/ebooks/apachesolr

Also the Apache Solr for Indexing How To has been recently released publicly: https://www.packtpub.com/mapt/book/Big%20Data%20&%20Business%20Intelligence/9781782164845/1

Excellent book, take some time to read it and you will learn how to do it.

**Comment by ZivHsu** [comment]
@xavier-morera 
Thanks, 

I created a binary  fields on my solr schema

I just uses WebRequest to post data on my solr to index data and is work,

but if i need to post binary data to solr,

how to do it?

**Comment by xavier-morera** [comment]
Extract request handler. Mentioned it in an older comment

**Comment by ZivHsu** [comment]
@xavier-morera 

I've see the Extract request handler in Solrnet,
but i don't understand this for what?

if i want to post SchemaField List object uses WebRequest to my solr for index
how to make it work?


my object :
    public class SchemaField
    {
        public virtual string id { get; set; }
        public virtual string title { get; set; }
        public virtual string content { get; set; }
        public virtual string author { get; set; }
        public virtual string editor { get; set; }
        public virtual DateTime created { get; set; }
        public virtual DateTime last_modified { get; set; }
        public virtual string links { get; set; }
        public byte[] docbinary { get; set; }
        public virtual string dynamicFieldTest_s { get; set; }
    }

Thanks

**Comment by xavier-morera** [comment]
Here you go https://github.com/mausch/SolrNet/blob/master/Documentation/Extract.md

**Comment by ZivHsu** [comment]
Hi @xavier-morera 

When I use 

            Product SchemaFields = new Product();
            SchemaFields.id = "http://google.com";
            SchemaFields.title = "Deep.pdf";
            SchemaFields.content = "asdrgtrgtggreg rgegerg rger gee";
            SchemaFields.author = "Ziv Hsu";
            SchemaFields.editor = "Ziv Hsu";
            //SchemaFields.docbinary = SchemaFieldsData;
            //SchemaFields.created = DateTime.Now.ToString("yyyy-mm-ddThh:mm:ssZ");
            //SchemaFields.created = DateTime.Now;
            //SchemaFields.last_modified = DateTime.Now;
            SchemaFields.links = "http://google.com";
            SchemaFields.dynamicFieldTest_s = "DynamicField Test1";

            Startup.Init<Product>("http://myhost:8983/solr");
            var solr = ServiceLocator.Current.GetInstance<ISolrOperations<Product>>();
            solr.Add(SchemaFields);
            solr.Commit();

to add data I will get 404 error,
and i see the url is http://myhost:8983/solr/update?version=2.2

how to fix this?

**Comment by xavier-morera** [comment]
Hi @ZivHsu 

For that kind of support, please post to StackOverflow.com

**Comment by ZivHsu** [comment]
Hi @xavier-morera 

I has search on StackOverflow.com but still not find the solution...

can you teach me how to fix that?

Thanks

**Comment by xavier-morera** [comment]
Hi @ZivHsu, as much as I would like to, I am up to my eyeballs on work on two projects and I have no one to help me, so I have to test, debug, try again until I solve my issues - I basically would love to have people to help me too but I just need to keep trying.

What I recommended is that you post in StackOverflow your question, describing it really well and usually there is someone with a bit more time happy to help. 

Good luck!

**Comment by ZivHsu** [comment]
@xavier-morera 

Thanks for your kind help

**Comment by ZivHsu** [comment]
@xavier-morera 

sorry i need to help

I use solrnet to index data like below :

            var data = new Dictionary<string, object> {
                {"id", "http://google.com/link1"},
                {"title", "test.pdf"},
                {"content", "abcdefghijk"},
                {"author", "Ziv Hsu"},
                {"editor", "Ziv Hsu"},
            };
            var solrFacility = new SolrNetFacility("http://mysolr:8983/solr/testcollection");
            var container = new WindsorContainer();
            container.AddFacility("solr", solrFacility);
            var solr = container.Resolve<ISolrOperations<Dictionary<string, object>>>();
            solr.Add(data );
            solr.Commit();

It's work;

but if I have a object list need to index 
is not work it'll get 400 code like below:

    public class LSchemaField
    {
        public List<SchemaField> SchemaFieldList = new List<SchemaField>();
    }
    public class SchemaField
    {
        public virtual string id { get; set; }
        .....
    }

            LSchemaField SchemaFieldList = new LSchemaField();

            SchemaField SchemaFields = new SchemaField();
            SchemaFields.id = ....;         
            SchemaFieldList.SchemaFieldList.Add(SchemaFields);

            SchemaField SchemaFields2 = new SchemaField();
            SchemaFields2.id =....;
            SchemaFieldList.SchemaFieldList.Add(SchemaFields2);

            var solrFacility = new  SolrNetFacility("http://mysolr:8983/solr/testcollection");
            var container = new WindsorContainer();
            container.AddFacility("solr", solrFacility);
            var solr = container.Resolve<ISolrOperations<LSchemaField>>();
            solr.Add(SchemaFieldList );
            solr.Commit();


Can it add a object list?

**Comment by mausch** [comment]
What is the error description? Check the Solr log if necessary.

**Comment by xavier-morera** [comment]
Closing as it has an answer in StackOverflow.
