### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by hheexx** [SolrNet/SolrNet#256]
Any plan for it?

**Comment by isbirkan** [comment]
Bump! 
I am currently trying to integrate with .NET Core. It would have been helpful to have this implemented already.
I will directly call the cloud through HTTP requests until then, since this is the core of the implementation itself.

**Comment by ErwinSteffens** [comment]
Here some interest too! We need this for a project. I think the `SolrNet` and `SolrNet.DSL` project are portable. I think there can be some problems with the build system and al tooling around it. 

We are trying to extract these two libraries from the project and integrate it directly it our project. When we have it working we can share it back if there is any interest.

**Comment by justinhp** [comment]
We are building some new projects and would like to use .NET Core, however, we are unable to due the incompatibility.  Are there any plans for it?

**Comment by mhov** [comment]
My money is on No, no plans to support .Net Core.  `SolrNet.csproj` is still targeting .Net 3.5.  Anyone is free to fork it and try for themselves though.

**Comment by neatnerd** [comment]
A related question is would it be possible to actually split this repository to multiple repositories? It would ease the porting process. For example, about Ninject integration we can forget for now, but it is still the part of the main repostiory, wouldnot it be better to move it to a separate repository?

**Comment by xavier-morera** [comment]
At this point what I believe would be better is to get SolrNet upgraded to newer versions. I am kind of stuck on that point in case someone wants to help

**Comment by neatnerd** [comment]
newer versions in what sense? Solr new version or .NET targets?

**Comment by xavier-morera** [comment]
To .NET 4.6. I am having some issues with the tests. Yesterday a fix was provided, I am going to take a look: https://github.com/SolrNet/SolrNet/issues/283

**Comment by xavier-morera** [comment]
Released in 0.7.1
