### ISSUE TITLE
Error 404 Not Found in all Actions

### ISSUE THREAD

**Issue by atmike** [SolrNet/SolrNet#257]
Hi 
I have setup my Solr 6.2.1 as describte on the Website and when I call the Search via URL => http://localhost:8983/solr/qms/select?q=name:"A Clash of Kings" it returns the following XML =>
`<?xml version="1.0" encoding="UTF-8"?>
-<response>
-<lst name="responseHeader">
<int name="status">0</int>
<int name="QTime">373</int>
-<lst name="params">
<str name="q">name:"A Clash of Kings"</str>
</lst>
</lst>
<result name="response" start="0" numFound="0"/>
</response>`

But when I use SolrNet I just get the Error 404 and there is nothing in Solr log files.

**Code**
`Startup.Init<Product>("http://localhost:8983/solr/qms/");`

`var p = new Product { Id = tadd.Text, Name = "xyz" };
var solr = ServiceLocator.Current.GetInstance<ISolrOperations<Product>>();
solr.Add(p);
 solr.Commit();
`
**or**
`var solr = ServiceLocator.Current.GetInstance<ISolrOperations<Product>>();
var results = solr.Query(new SolrQueryByField("id", "xyz"));
`
It takes ca. 5sec bevor the error comes up.

**Error**
 `An unhandled exception of type 'SolrNet.Exceptions.SolrConnectionException' occurred in SolrNet.dll
Additional information: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>

<p>Problem accessing /solr/qms//update. Reason:
<pre>    Not Found</pre></p>

</body>
</html>`

does any one has an Idea what I'm doning wrong?

regards

**Comment by anshuforu** [comment]
I am facing similar error.  I have solr 6.2.1 and running the same without tomcat. I can access the solr using "http://localhost:8983/solr". It works fine. But when I call "solr.Delete(SolrQuery.All)" in Global.asax.cs in SampleSolrApp application which actually calls "connection.Post("/update", deleteNode.ToString(SaveOptions.DisableFormatting))" in DeleteCommand.cs file of SampleSolrApp and throws following error: "HTTP ERROR 404". Please tell me what is wrong I am doing? Thanks

**Comment by mausch** [comment]
@atmike it might be possible that the double slash in the URL causes this.

@anshuforu if everything except for delete works fine, there might be some unhandled breaking change in Solr, though I'd find that weird. Can you use [Fiddler](http://www.telerik.com/fiddler) to see the exact request being generated by Solr?

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
