### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by SumanAvula** [SolrNet/SolrNet#259]
Hi Team,

Solrnet.dll was working with visual studio 2012 and when i have opened my solution in visual studio 2015, i am getting the below error if i did build the solution.

Could you please help me to resolve the below error.
**An exception of type 'System.IO.FileNotFoundException' occurred in SolrNet.dll but was not handled in user code

Additional information: Could not load file or assembly 'HttpWebAdapters, Version=0.4.0.2002, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.**

**Comment by xavier-morera** [comment]
Should be in the included libraries.
