### ISSUE TITLE
Can the default field be changed?

### ISSUE THREAD

**Issue by ca0abinary** [SolrNet/SolrNet#260]
Firstly, thanks! This is a really cool project.

Is there a way to change the default field from `id` to a custom value? My core doesn't use `id` as a field name, but i would like to use .Query().

**Comment by ca0abinary** [comment]
Kind of solved my own problem. Using

`_docs.Select().Query($"myIdField:{value}").Execute().Document()`

Works nicely. Is it possible to use something like:

`_docs.Select().Query(x => x.MyIdField, value).Execute().Document()`

instead? When I tried this it discarded my lambda expression in the URI generated for Solr.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
