### ISSUE TITLE
nuget CommonServiceLocator  Dependencies should be >= 1.0.0

### ISSUE THREAD

**Issue by jrt324** [SolrNet/SolrNet#264]
Last nuget version SolrNet 0.5.0-alpha2

> Dependencies
> CommonServiceLocator (= 1.0.0)

the  CommonServiceLocator  Dependency should be >= 1.0.0

**Comment by Wintermute79** [comment]
Yes, previous versions had >= 1.0.0, very annoying

**Comment by gjunge** [comment]
Landed in master branch through PR #292 
Will be part of next release

**Comment by gjunge** [comment]
Included in next release.

**Comment by xavier-morera** [comment]
Completed in 0.7.1
