### ISSUE TITLE
Autofac version is not compatible with the latest versions

### ISSUE THREAD

**Issue by alex-training** [SolrNet/SolrNet#268]
Hi @mausch 
There is a pitty issue with Autofac (https://github.com/autofac/Autofac/issues/520) which doesn't allow to use SolrNet Autofac nowadays.

I've created a pull request to fix this:
https://github.com/mausch/SolrNet/pull/267

Theoretically we can upgrade Autofac up to 4.x versions, it's up to you.

Also I would recommend to specify Autofac dependency in the nuget package more softly, instead of strict version (=) use "no less that x" (>=) or range (3.x <= version <= 4.x).

**Comment by xavier-morera** [comment]
Currently working on it on branch https://github.com/SolrNet/SolrNet/tree/net-update-plus-autofac-ninject

**Comment by gjunge** [comment]
Fixed in #286
