### ISSUE TITLE
Is SolrNet still alive?

### ISSUE THREAD

**Issue by alex-training** [SolrNet/SolrNet#269]
Hi guys!

I have a doubt about this project state. Is it still in good health? 
Last commit was 11 months ago, also there is no answers on my questions and pull requests.

**Comment by xavier-morera** [comment]
Hi Alex, I received an email a few months ago from @mausch where he told me he had some health issues that had him separated from the keyboard, but that he wanted to move SolrNet to an organization and have multiple people helping it move forward. I would like to participeate but we need for Mauricio to set up as an organization. Mauricio: is this something that we could do?

**Comment by ham3dz** [comment]
Hi,

In my opinion this project goes no where because it has a lot of bad practices in its core design and without any new activity, it's so behind. I would love to participate and make it better though.

Also, I'm thinking about designing a new project from scratch to fix all those bad practices.

**Comment by xavier-morera** [comment]
@ham3dz I actually think it is a really good project. It is in production at enterprise level in projects where I have participated. It is a huge undertaking, and I believe it should be kept alive and evolve with the new versions of Solr. 

Also, have you considered how much time would it take for you to start from scratch? Probably a year or two if you are really really dedicated. I don't think starting from scratch is viable unless you have corporate sponsorship.

**Comment by ham3dz** [comment]
@xavier-morera I agree, at my workplace we are using it too. But it needs more attention.
By working harder we can keep it alive, but like I said before there is no new activity for 11 month.

By the way, don't get me wrong, I just thought about. I really don't have time or money to design something this huge from scrratch ;)

**Comment by xavier-morera** [comment]
Correct, we are in Mauricio's hands right now to keep it alive.

**Comment by mausch** [comment]
I've just moved the SolrNet repo to its own organisation. I invited @xavier-morera as the first member. More will surely follow soon.

I offer my humble apologies to everyone. For whatever reasons, my inaction has led to many problems for all SolrNet users. 
I do agree with @ham3dz that the code has design issues. When I wrote this project about 10 years (!) ago I had a very different perspective on how to write code. I've been tempted myself many times to start this project from scratch. But the truth is, with all its flaws it still gets the job done, it is still quite flexible, and people already using it would have migration issues if they had to switch to an entirely new library. So I think it is still worth maintaining, but of course that doesn't preclude anyone else starting a more modern project.

**Comment by xavier-morera** [comment]
@mausch thank you very much. I kind of disagree on the design flaws. I think that one does its best with its best intentions at a precise time with the available resources at the time and your effort created something great. 

I just accepted your invitation and will start to work reviewing to see who else might want to help. Anyone has any suggestions to offer at this point? I believe SolrCloud and some pending breaking changes at this point will be the first step.

**Comment by ham3dz** [comment]
@xavier-morera I extended SolrNet and implemented "Atomic Update" in one of my projects. I can share it if anyone interested.

**Comment by xavier-morera** [comment]
@ham3dz please do. One thing that is needed for all pull requests is to have tests so if you can provide with tests using the framework used by the creator of SolrNet that will help keep the quality of the project up.

**Comment by gjunge** [comment]
First off, thanks @mausch for releasing your project to the community, you've created a really helpfull project for many of us.

Hi @xavier-morera and thanks for taking up this important task.

#91 Async support has been a hot topic. 
Yet a decision has to be made how to implement it. My preference has always been to upgrade the project to .NET 4.5 , and nowadays also use the new HttpClient which might bring us closer to .NET Core support.

If we want to support .NET 3.5 we can add conditional compilation statements, but this might make  the code a bit less clean. 

So moving the project forward, a decision has to be made on going to .NET 4.5 or staying on .NET 3.5

Your thoughts?

**Comment by kevinha** [comment]
Hi,
I think comprehensive build instructions would be a good idea. I recently tried to patch the spellcheck parser for > 4 solr and didn't have time to work out how to get the correct version of FAKE installed. Upgrading to the latest version of FAKE would be good. Making the project easy to build would help to promote contributions.

**Comment by TheFairey** [comment]
Hi

I'm also a fan of this library but have recently considered moving to another c# based library for one reason and that is the dependency on an older version of the commonservicelocator which basically prevents me from using unity for DI.

Sadly I lack the c# to help in this regard!

Si

**Comment by Fedtekansler** [comment]
Hi,

The SolrNet integration for StructureMap is quite hard to integrate in my current project. The SolrNetRegistry is based on structuremap =~ 2.6.2 (or something similar). In the Episerver project, I am working on, I can't downgrade to that version, as Episerver depends on 3.x at minimum. 

I think the main issue is that some of libraries have been moved around in newer version of StructureMap. 

The multi core - multi instance setup is very valuable to me, but it's very difficult to use in modern projects, unless I'm doing something wrong? 

SolrNet is really a strong tool and the performance is great too, so the design flaws are few in my opinion.

// Peter

**Comment by dgauss** [comment]
Hello,
I am also using this tool in an enterprise level application and would like to keep seeing it move forward.  I am "full stack" for whatever that means anymore but have plenty of practice in C# and the .net framework.  Getting better at Solr and the Hadoop platform in general.  I wouldn't mind giving up some weekend hours if you have some code to write. 
Thanks, 
Eric

**Comment by xavier-morera** [comment]
Understood both, and I am an enterprise user too. I am about to finish one of my two current projects next week. I am going to have a lot of free time after that as I am off from work at noon everyday so have all afternoons to work on this. My plan is to pick this up as a priority May 15.

**Comment by janhoy** [comment]
Suggestion: Setup a gitter chat for the project, to enable quick interaction between users, right from this repo

**Comment by xavier-morera** [comment]
Good suggestion, I would've been glad to get a bit of help figuring out why the build was failing, which turned out to be Gallio does not support VS 2015 PDBs.

Although I would prefer Slack and can do it right away, it integrates well. Is there an advantage of using gitter chat?

**Comment by TLogik** [comment]
Hi
I am also using Solrnet at a enterprise level to, and even thou we had some issues getting it up and running as we need it to, we are quite happy with it.
we have already contributed a bit to the codebase and would like to keep on contributing and help bring SolrNet into the future.

**Comment by xavier-morera** [comment]
There are two things I am working on:
- upgrading .Net version
- publishing to Nuget

If you can help on either, that would be great. Let me know if you have some availability

Xavier

--------------------------------------------

**Comment by TLogik** [comment]
Hi Xavier
I am leaving for a 3 week holyday (far away from home) but when back ill look into the issues stated below and report back on what I can commit to.

/Thomas

**Comment by xavier-morera** [comment]
Alive and kicking because of @gjunge
