### ISSUE TITLE
Ninject Version update (SolrNet.Ninject) to a more recent one. 

### ISSUE THREAD

**Issue by stanuku** [SolrNet/SolrNet#271]
Similar to #268

**Comment by xavier-morera** [comment]
Currently working on https://github.com/SolrNet/SolrNet/tree/net-update-plus-autofac-ninject

**Comment by xavier-morera** [comment]
Please take a look at the branch and let me know if you can help on updating Ninject

**Comment by gjunge** [comment]
Will be fixed by: #286

**Comment by xavier-morera** [comment]
Released in 0.7.1
