### ISSUE TITLE
Targeting .NET Standard Library

### ISSUE THREAD

**Issue by stanuku** [SolrNet/SolrNet#272]
It will be a great feature to analyze the gaps and support/target the .NET standard library.

Are there any plans to that effect?

**Comment by xavier-morera** [comment]
That's part of the idea of the issue that I opened today: https://github.com/SolrNet/SolrNet/issues/270

Determine what is the need and prioritize. Would you please help by filling out the form and, if possible, ask other SolrNet users to provide their feedback?

**Comment by xavier-morera** [comment]
Released in 0.7.1
