### ISSUE TITLE
Binary response format (SMILE)

### ISSUE THREAD

**Issue by janhoy** [SolrNet/SolrNet#274]
Solr has support for SMILE response-writer, which is a compact "binary json" protocol that should give similar performance improvements as JavaBin (#83) 

See https://cwiki.apache.org/confluence/display/solr/Response+Writers#ResponseWriters-SmileResponseWriter

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
