### ISSUE TITLE
SolrNet issues GET requests even though PostSolrConnection is registered 

### ISSUE THREAD

**Issue by attodorov** [SolrNet/SolrNet#276]
Hi,

I'm having the following issue. I use SolrNet 0.4.0.2 and I would like to change from GET to POST because my queries can get large enough to surpass the default GET header size. I can certainly change that limit in jetty, but i would just like to switch to POST, to be on the safe side. So i am doing the following:

            var container = new WindsorContainer();
            var solrFacility = new SolrNetFacility(url);
            solrFacility.AddCore(url, typeof(Dictionary<string, object>), url);
            container.AddFacility(solrFacility);
            container.Register(Component.For<ISolrConnection>()
    .ImplementedBy<PostSolrConnection>().DependsOn(Parameter.ForKey("serverUrl").Eq(url)));
            var solr = container.Resolve<ISolrOperations<Dictionary<string, object>>>(url);

After that, requests are still GET, not POST. I assume this is a bug in SolrNet? 

Thanks
Angel

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.

**Comment by Reddyo** [comment]
I am having the same issue. My code is almost identical to op's except that I am using a custom object instead of a "Dictionary<string, object>" as the object type yet the requests being sent from SolrNet are still GET and not POST as desired. Has this been resolved yet or am I missing something?
