### ISSUE TITLE
Nuget package for release 0.5.1

### ISSUE THREAD

**Issue by Edminsson** [SolrNet/SolrNet#279]
Hi,
Very excited about the revival of Solrnet!
Is there a new version of SolrNet Nuget package on the way?

**Comment by xavier-morera** [comment]
Hi @Edminsson, it is in the works. However I am in the process of getting the permissions to get it released. In theory it will take a few weeks

**Comment by Edminsson** [comment]
Thanks @xavier-morera. Looking forward to it.

**Comment by xavier-morera** [comment]
Will tackle also: https://github.com/SolrNet/SolrNet/issues/264

**Comment by dkapsalis** [comment]
Looking forward to this.  About to start a Solr backed project and would be nice to have the nuget package.

**Comment by alduehr** [comment]
@xavier-morera Do you have an update on this?  We are anxiously awaiting this

**Comment by xavier-morera** [comment]
I got permissions two days ago for Nuget. I am in NY this week on site and will work on this next week when I get back. I have activities at night and then travel back.

**Comment by xavier-morera** [comment]
Nuget updated to 0.7.1. Will configure automatic deployments with AppVeyor in the short term
