### ISSUE TITLE
Move SampleSolrApp into different Repository

### ISSUE THREAD

**Issue by gjunge** [SolrNet/SolrNet#288]
In order to clean up the repo, I suggest moving the SampleSolrApp and its dependencies to it's own repository (ex. SolrNet/SampleSolrApp). 

The Sample Solr App can reference Solr by using nuget, just like any other user would do.

I'm more than happy to help/do the migration, once the extra project is set up.

**Comment by xavier-morera** [comment]
Excellent idea. The current master in SolrNet also has a 4.x version of Solr which can be moved here as well.

Thank you very much, here is the repository:
https://github.com/SolrNet/SolrNetSampleApps

Please put the current SampleSolrApp in a folder of its own so that other samples can be added when required

Also on Monday I will work on Nuget

**Comment by gjunge** [comment]
- I actually started working on getting solr upgraded to 6.6  , have it working in theory.
- solr itself should be in both repo's, since the integration tests use solr as well.

**Comment by gjunge** [comment]
@xavier-morera  I'll move the SampleSolrApp version from solrnet/net-update-plus-autofac-ninject

**Comment by xavier-morera** [comment]
Great work! Here is what I think are the next steps:
1. Get current version in Nuget (just got keys today, will try it out tonight)
2. Release the branch that upgrades to 4.6, including Nuget (but not yet Solr 6.6) Having this is as a standalone release helps those that are currently using SolrNet with older versions as it has minimal changes
3. Go for SolrCloud (branch already waiting for review)
4. Then Solr 6.6 (is it possible to do this in a separate branch, just to get other people to test?)

Thanks a lot! Great contributions

**Comment by gjunge** [comment]
1. Regarding Solr 6.6, I didn't actually mean solrnet support for it (if necessary), but rather, upgrading the solr version inside the project to 6.6  . Anyway this will lay the basis for code support for 6.6, so yet when we get to number 4 I'll do so.
2. I'm in rather advanced stages of async support (see https://github.com/gjunge/SolrNet/tree/async-support ) . I'm only all the time facing issues with our unit tests and build system. 
MbUnit is not really .net 4.6 friendly, and I feel we are reaching its EOL boundaries.
3. So I also started kind of a bomb shell project, converting all unit tests to xunit, and getting them to run in AppVeyor.  I am aware of #175 , but it seems that 2.5 year later, and 10 year after creating some those unit tests, xunit is in good shape to take over.

**Comment by xavier-morera** [comment]
Understood on 1. Then I suggest Solr should be moved to the SolrNetSampleApps to minimize size of main repository.
Great on 2. Understood on XUnit. I am totally in favor of XUnit. The creator of this project, Mauricio, favored MbUnit and had strong reasons to do so, but development ceased on MbUnit so worth moving to XUnit at this point. 
So on 3. then it is better to have both in parallel and move little by little from MbUnit to XUnit to do a controlled and progressive migration

**Comment by gjunge** [comment]
1. Well, actually the solr instance is in use by the integration tests (which currently ,  with MbUnit,  partially fail), see also #289  . Maybe in the future we can create some (Powershell) scripts that downloads and sets solr up when the integration tests are run for the first time, for now I think that is a bridge too far.
2. and 3. See #289, it is actually pretty far along.

Different question all together: Are you still using the FAKE/Build scripts? I believe that most of what it does can be moved over to different areas. 
- NuGet packaging, add a standard nuspec file to the various projects, and let let AppVeyor do the publishing. This seems a much more standard way to do it. This way a user can even decide to publish the nugets of his branch to a private nuget server easiliy.
- Running test: from the IDE and in AppVeyor
- Building: from the IDE and in AppVeyor
- Running integration tests: can build a script for that
- Running the sample app, will be separated anyway.
- ILMerge: needed for what?
What is your opinion on the matter?

**Comment by xavier-morera** [comment]
Answers inline
- NuGet packaging, add a standard nuspec file to the various projects, and let let AppVeyor do the publishing. This seems a much more standard way to do it. This way a user can even decide to publish the nugets of his branch to a private nuget server easiliy.

Agreed

- Running test: from the IDE and in AppVeyor

I agree, however Mauricio had a different opinion on running from the IDE. However let's move forward and if the original creator wants a different direction we can start a talk on the matter

- Building: from the IDE and in AppVeyor

Agreed

- Running integration tests: can build a script for that

Sounds good, especially not having Solr as part of the repository

- Running the sample app, will be separated anyway.

Agreed, I can move it tonight or tomorrow and commit.

- ILMerge: needed for what?

I do not know, need to review

**Comment by mmoldabe** [comment]
Cannot find SampleApp in both repositories. Do You update app during development?

**Comment by gjunge** [comment]
@xavier-morera A PR is still waiting to be accepted: https://github.com/SolrNet/SolrNetSampleApps/pull/1

**Comment by mmoldabe** [comment]
Also, I've found other [commit ](https://github.com/SolrNet/SolrNet/tree/f3b78da9f3075cf73a28242835c96f338d715007) and tried to run SampleSolrApp from given **.bat** file -- getting errors, web page tells that **app.config** is wrong.

**Comment by xavier-morera** [comment]
@gjunge thanks, done.

**Comment by camelofcode** [comment]
You should update the docs that reference the old location, I was tearing my hair out for a minute.

**Comment by xavier-morera** [comment]
Done @camelofcode 

Sorry for that. Thank you
