### ISSUE TITLE
Migrate unit tests to xUnit

### ISSUE THREAD

**Issue by gjunge** [SolrNet/SolrNet#289]
Due to the fact that MbUnit is not anymore being maintained for the last 4 years, and SolrNet is moving forward, using newer technologies, it is advisable to move to a more recent and well maintained unit testing platform that is ready for the future.

I've started working on migrating all unit and integration test, and it currently all compiles (see branch: https://github.com/gjunge/SolrNet/tree/convert-to-xunit , and see almost all unit test running passing:  https://ci.appveyor.com/project/gjunge/solrnet/build/tests)

Items to be dealt with before ready to merge:
- [x] Convert all tests to xUnit
- [x] Fix nHibernate tests (excluded tests from appveyor. nHibernate integration seems to be obsoleted anyway)
- [x] Remove tests from Build scripts (build.fsx)
- [x] Add appveyor.yml that is currently in use, so the Integration test category can be programmaticely set to be ignored.
![image](https://user-images.githubusercontent.com/194466/29252045-de4523e6-8068-11e7-9a16-93c5e8fe94f1.png)
- [x] Create Integration test runner. For integration test we need to start the solr instance, run the test marked under category "Integration", and then stop the solr instance. Powershell?

[![Build status](https://ci.appveyor.com/api/projects/status/vc4hrswj8a7wgmwx?svg=true)](https://ci.appveyor.com/project/gjunge/solrnet)

**Comment by xavier-morera** [comment]
Released in 0.7.1
