### ISSUE TITLE
Add SolrCloud support

### ISSUE THREAD

**Issue by gjunge** [SolrNet/SolrNet#305]
See branch: https://github.com/SolrNet/SolrNet/tree/solrcloud

- [x] Merge develop branch into solrcloud branch to get it up to date
- [x] Add Async
- [x] Create unit tests
- [ ] Create integration tests (see #299)
- [ ] Add DI support for our main DI's: Windsor, Ninjeft, Autofac, Microsoft.Extensions.DI
- [x] Create nuspecs for all new projects.

**Comment by gjunge** [comment]
@xavier-morera Started working on merging and getting it up to date. So far, compilation wise, no big issues are expected, despite having to add async, changing out an obsolete zookeeper library, and upgrading all other dependencies. 

Once all compiles I will publish my branch and create an initial pull request.

**Comment by xavier-morera** [comment]
That is great. With that pull request I will ask those who contributed to that change to take a look as they are using it in production.

**Comment by gjunge** [comment]
@xavier-morera  See PR comments. 

Open items:
- Naming, do we go for SolrCloudNet or SolrNet Cloud or SolrNetCloud ? Currently the contributors went for SolrNet.Cloud
- I didn't run any integration tests.
- Currently only Unity and CommonServiceLocator are implemented as DI. 
- They use a zookeeper library `ZooKeeper.Net` which is not `netstandard` compliant, and is totally synchronous. There is another one called `ZooKeeperNetEx`, more downloads, newer, supports `netstandard` but very java-y in its syntax (they name it as a pro), and async only, meaning we need to rewrite some "init" code, which is sync only.
- I don't see a reason not to merge it to the master branch. Except for a small change in the main SolrNet library (creating a base class for DRY),  the code is seperate from the rest.

**Comment by xavier-morera** [comment]
@gjunge regarding your comments
Open items:

> - Naming, do we go for SolrCloudNet or SolrNet Cloud or SolrNetCloud ? Currently the contributors went for SolrNet.Cloud

SolrNet.Cloud sounds pretty good

> - I didn't run any integration tests.

Understood. @AlexeyKozhemiakin & dkrupnou you worked on the original SolrCloud implementation. Are you able to comment on this code? Do you use it in production? Any issues that you have identified? @gjunge is doing a lot of work to move the project forward 

> - Currently only Unity and CommonServiceLocator are implemented as DI. 

I think this is fine, anyone who needs a different DI can help implement

- They use a zookeeper library `ZooKeeper.Net` which is not `netstandard` compliant, and is totally synchronous. There is another one called `ZooKeeperNetEx`, more downloads, newer, supports `netstandard` but very java-y in its syntax (they name it as a pro), and async only, meaning we need to rewrite some "init" code, which is sync only.

@gjunge what would be your recommendation? IMHO making the library netstandard compliant is a bigger priority. how much work do you believe rewriting the init code will take?

- I don't see a reason not to merge it to the master branch. Except for a small change in the main SolrNet library (creating a base class for DRY),  the code is seperate from the rest.

Ok, I will merge. Just give it a day or two to get the original contributors I referenced a couple of days to comment.

**Comment by gjunge** [comment]
@xavier-morera the coming month and a half I will be less productive/more on the background. I am leaving on holiday and have a few deadlines myself. 

If my input is needed let me know and I will try to answer as soon as I can.

**Comment by xavier-morera** [comment]
@gjunge thanks for letting me know. I am in the same boat. I need to finish a project before September 15 - and it is looking too tight - as I am going on the road for three weeks. First, Pluralsight Live, then a training for Accenture and then Strata Hadoop so that is why I am so slow 

I will try to respond as soon as possible. Enjoy your holiday
