### ISSUE TITLE
Create a 0.7.1 release in master branch

### ISSUE THREAD

**Issue by gjunge** [SolrNet/SolrNet#308]
I think we should continue creating "releases" on the master branch. This shows also what the last version was, and also gives a convenient way to get get to a certain release from the master branch.

![image](https://user-images.githubusercontent.com/194466/29822028-b54e56d0-8cd2-11e7-935f-7cce1e6097e1.png)

**Comment by xavier-morera** [comment]
Agreed, thanks for pointing it out

![image](https://user-images.githubusercontent.com/7174278/29838760-534c2e58-8cb9-11e7-97a7-0ffab2019097.png)
