### ISSUE TITLE
How to integrate Solrcloud support into a project

### ISSUE THREAD

**Issue by LoadGik** [SolrNet/SolrNet#313]
Hello everyone.

After reading this issue #174, is it possible to use the SolrClound branch today for my developments?

If so, could you please explain to me how to integrate this version into a project?

I would also like to ask you if this version is compatible with version 4.5 of Net Framework.

And thank you for the work you have done.

**Comment by xavier-morera** [comment]
Hello @LoadGik, the answer is yes, please use SolrCloud branch for development. We will promote once it has received more testing. This is compatible to 4.5. 

Please look at the functionality in SolrNet.Cloud for the objects necessary to use SolrCloud. Once some more testing takes place, we will include in the instructions additional samples.

**Comment by LoadGik** [comment]
Hello Xavier,

Thank you for answering.

But unfortunately I am unable to generate the DLLs since the project I recovered on the "SolrCloud" branch.

There are a number of things that I do not understand very well and I do not know how to integrate this version into my project.

Is it possible to directly retrieve the NuGet package or the DLLs of this version.

Or detail the procedure to follow, without wanting to abuse your time ...

Thanks in advance no matter what your answer.

**Comment by xavier-morera** [comment]
Hi @LoadGik 

I cannot help for the next week or so. I really apologize but I am on a 3 week trip with very little time and I also need to catch up on the SolrCloud branch. 

If you are in a hurry, you can set up a load balancer in front of your SolrCloud deployment and it should work fine. 

Also maybe @alex-training @AlexeyKozhemiakin @janhoy @dkrupnou could be able to help on guidance if they have a minute as they were part of the SolrCloud discussion and coding. Either one of you can guide @LoadGik?

**Comment by LoadGik** [comment]
No problem, thank you for your return :)

**Comment by gjunge** [comment]
We now have a little bit of documentation here: https://github.com/SolrNet/SolrNet/blob/master/Documentation/Basic-usage-cloud.md
and see here: https://github.com/SolrNet/SolrNet#solrcloud for a list of nuget packages for SolrNet.Cloud
