### ISSUE TITLE
NuGet package "SolrNet.Microsoft.DependencyInjection" contains wrong "Unity"-assembly

### ISSUE THREAD

**Issue by earloc** [SolrNet/SolrNet#314]
Our Team just tried to integrate SolrNet with above nuget-package, but couldn´t find the documented extension-method to register with ServiceCollection.

A look into the nuget-package revealed that it contains **Unity.SolrNetIntegration.dll** instead of **Microsoft.DependencyInjection.SolrNet.dll**.

As a workaround we cloned the repo and are referencing the correct assembly, but it would help very much if you guys could have a look into this.

The issue seems to be in the corresponding [nuspec-file](https://github.com/SolrNet/SolrNet/blob/master/Microsoft.DependencyInjection.SolrNet/Microsoft.DependencyInjection.SolrNet.nuspec) - Lines 20 - 22. 

(Don´t know your nuspec/nuget build pipeline, otherwise we might have a look on our own, if you´re interested in a PR. However, we would need some guidance about the publishing-flow for nuget-packages)

(I guess _netstandard_-ization is causing a lot of confusion these days ;) )

Cheers

**Comment by xavier-morera** [comment]
Thanks for this. Will take a look, can you please fork the project and make a branch with this fix so that I can check it out? And yes, confusion indeed.

**Comment by earloc** [comment]
OK, give me some time (we shortcutted the issue by currently referencing the manually built assembly).

I think the main "problem" is to decide wether to utilize the "old"-nuspec-based packaging vs. the "new" VS-integrated mechanism (via dotnet-core tooling).

Will investigate both path´s (probably) this evening.

**Comment by gjunge** [comment]
That’s a typo (more like a post-copy/paste mistake) from my side. 
The nuspec file needs to be fixed, since AppVeyor uses the nuspec file to create NuGet packages and automate deployment to NuGet.

**Comment by earloc** [comment]
Yep, just got that fixed in #315.
(These are the kind of authoring-"bugs" that caused me switching to dotnet-tooling in some of my own packages)

The project doesn´t generate a XML-documentation-file, so that part is stripped out atm, as the missing file would prevent the package from creation.

**Comment by gjunge** [comment]
And somehow I remember fixing this bug already once. We had some merge issues and perhaps this change was reverted. 

Thanks for the fix!

**Comment by xavier-morera** [comment]
Thanks. Let me take a look. I made a mistake a while back on the merge so perhaps that was it.

**Comment by xavier-morera** [comment]
Completed, 0.8.1 released
