### ISSUE TITLE
Unable to install 0.8.1 via NuGet due to invalid dependency

### ISSUE THREAD

**Issue by CalMlynarczyk** [SolrNet/SolrNet#316]
When attempting to install 0.8.1 using NuGet, I receive the following error:

`Unable to resolve dependencies. 'SolrNet.Core 0.7.1' is not compatible with 'SolrNet 0.8.1 constraint: SolrNet.Core (= 0.8.1)'.`

It appears SolrNet.Core v0.8.1 has not been published to NuGet yet. https://www.nuget.org/packages/SolrNet.Core/

**Comment by xavier-morera** [comment]
Thanks @CalMlynarczyk 

I configured last night AppVeyor to publish automatically and there are two packages missing. I am working on figuring out how to fix it.

**Comment by xavier-morera** [comment]
@CalMlynarczyk can you check now. Both have been published to NuGet

**Comment by CalMlynarczyk** [comment]
Yea, it looks good. Thanks!
