### ISSUE TITLE
URL Encoding of special characters

### ISSUE THREAD

**Issue by Napkin41** [SolrNet/SolrNet#319]
I'm a bit new to the scene, and I've looked through other issues to see if mine is similar, but I could not find anything.

I'm trying to build a function into a facet query like this:
`var suggestionFacetFieldQuery = new SolrFacetFieldQuery("{!key=Contained_In_Industries+facet.contains=Entertainment}Industries");`

The desired request to Solr should reseble something like this:
`...&facet.field={!key=Contained_In_Industries+facet.contains=Entertainment}Industries...`

But instead, what solr.logs informs me is that it is receiving this from SolrNet:
`...&facet.field={!key%3DContained_In_Industries%2Bfacet.contains%3DEntertainment}Industries...`

The URL encoding of = and + are causing Solr to return some results that are wonky, and I'm wondering if there's a way to somehow prevent URL encoding of these characters?

I'm using SolrNet 0.4.0.4001 (From Nuget) and Solr 6

**Comment by Napkin41** [comment]
Turns out only the + was the problem. Replaced it with a space and I'm getting the functionality that I wanted. I'm not even sure why I added the + sign in the first place. Sorry to waste your time!

**Comment by xavier-morera** [comment]
Not a waste of time, sorry to be late to the party. Wasn't able to check in until today.
