### ISSUE TITLE
Support ConstantScore query

### ISSUE THREAD

**Issue by gjunge** [SolrNet/SolrNet#324]
See https://lucene.apache.org/solr/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-ConstantScorewith_

We have already support for the BoostQuery , which adds a boost to a query or part of it.
Solr also support setting a constant score to a (part of a) query.

> This is desirable when you only care about matches for a particular clause and don’t want other relevancy factors

**Comment by xavier-morera** [comment]
Merged into develop, courtesy of @gjunge
