### ISSUE TITLE
How to set POST request as default?

### ISSUE THREAD

**Issue by mmoldabe** [SolrNet/SolrNet#342]
Trying to set POST as default request type, but getting it wrong. Current container is Autofac.

```
var builder = new ContainerBuilder();
builder.RegisterType<PostSolrConnection>()
                   .Named<ISolrConnection>("SolrConnection")
                   .WithParameter("serverUrl", serverUrl);

builder.RegisterModule(new SolrNetModule(serverUrl));
var container = builder.Build();

var solr = container.Resolve<ISolrOperations<Product>>();

```

Still getting GET as default request. [This](http://bugsquash.blogspot.com/2010/12/customizing-solrnet.html)/[this](https://stackoverflow.com/questions/7583824/using-post-requests-to-solr-from-solrnet) links won't help.  I'm wondering if PostSolrConnection is included in lib.

How can I set POST request as default?

**Comment by mmoldabe** [comment]
@gjunge can you take a look, please?

**Comment by mmoldabe** [comment]
@gjunge @xavier-morera any thoughts on this issue? How can we use POST connection, where there are long queries? For example this case: I have a situation when I need to pass thousands of values in filters, but C# throws "URI long..." exception, before code starts to connect Solr server.

**Comment by xavier-morera** [comment]
@mmoldabe the creator of SolrNet has a nice post on the subject:

http://bugsquash.blogspot.com/2010/12/customizing-solrnet.html

**Comment by mmoldabe** [comment]
I've already read this. It won't help. PostSolrConnection is the part of SolrNet since that post. But, still, it won't work.

**Comment by mmoldabe** [comment]
That's why I'm asking you, as the main contributor of SolrNet. How does POST works now? @xavier-morera

**Comment by xavier-morera** [comment]
@mmoldabe I have not made any changes to POST recently. I will take a look this week as I will work on indexing samples for the sample apps.

**Comment by gjunge** [comment]
@mmoldabe We are using the PostConnection in production, though we are using Ninject.

This is my code snippet:
``` csharp
kernel.Load(new Ninject.Integration.SolrNet.SolrNetModule(url));

kernel.Rebind<SolrNet.ISolrConnection>().To<SolrNet.Impl.PostSolrConnection>().WithConstructorArgument("serverUrl",url);
kernel.Bind<SolrNet.ISolrConnection>().To<SolrNet.Impl.SolrConnection>().WhenInjectedExactlyInto<SolrNet.Impl.PostSolrConnection>().WithConstructorArgument("serverURL", url);
``` 
So here after registering the normal Ninject module (which binds the regular `SolrConnection`), I rebind the `ISolrConnection` to use the `PostSolrConnection`. 
But what is important is that I also state that the regular `SolrConnection` should be injected into the `PostSolrConnection` constructor.

I don't know how this translates to Autofac, but I hope it helps.

**Comment by mmoldabe** [comment]
@gjunge trying to run your snippet using Ninject Module, but getting same error as for Autofac:

> _System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1._  
>  in System.Xml.XmlTextReaderImpl.Throw(Exception e)
>    in System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
>    in System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
>    in System.Xml.XmlTextReaderImpl.ParseDocumentContent()
>    in System.Xml.XmlTextReaderImpl.Read()
>    in System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
>    in System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
>    in SolrNet.Impl.SolrQueryExecuter`1.Execute(ISolrQuery q, QueryOptions options) in C:\projects\solrnet-crl26\SolrNet\Impl\SolrQueryExecuter.cs:line 673
>    in SolrNet.Impl.SolrBasicServer`1.Query(ISolrQuery query, QueryOptions options) in C:\projects\solrnet-crl26\SolrNet\Impl\SolrBasicServer.cs:line 116
>    in SolrNet.Impl.SolrServer`1.Query(ISolrQuery query, QueryOptions options) in C:\projects\solrnet-crl26\SolrNet\Impl\SolrServer.cs:line 54
>    in SolrNet.Impl.SolrServer`1.Query(ISolrQuery q) in C:\projects\solrnet-crl26\SolrNet\Impl\SolrServer.cs:line 96

This is for standard _q=sample_ query. This happens for both Autofac and Ninject when trying to do PostSolrConnection.

**Comment by xavier-morera** [comment]
@mmoldabe that is a different issue, please add an extra param “wt” with value “xml”

options.ExtraParams = new KeyValuePair<string,string>[] {
    new KeyValuePair<string,string>("wt", "xml")
};

**Comment by mmoldabe** [comment]
@xavier-morera it worked! Thank you! May I ask what was the problem? Never thought that it could be for ExtraParam (like optional). This is the requirement for POST?

**Comment by xavier-morera** [comment]
@mmoldabe glad to hear! Solr used to have XML as default wt, but it was changed to Json. This was fixed in the latest SolrNet version

**Comment by mmoldabe** [comment]
@xavier-morera oh, I see. So, this means that latest SolrConnection uses JSON as default, but PostSolrConnection still use XML, right?

**Comment by xavier-morera** [comment]
@mmoldabe No. everything uses XML, just that with newer Solr versions it is required to specify the wt to get the response in XML The fix in SolrNet just manually adds wt.

Also you mentioned that you did not see anything in Fiddler. Are you testing using a local Solr instance?

**Comment by mmoldabe** [comment]
@xavier-morera  Now I understand. This is quite helpful. I was testing both local and Windows Server services instances. 
I'm new to Solr and SolrNet, now Im going to learn and contribute SolrNet, guys!

**Comment by xavier-morera** [comment]
@mmoldabe excellent! Thanks!

**Comment by hrishikeshtt** [comment]
Hi I have updated the solrnet dll from 0.4.0 to 1.0.17
But now I am getting a different error 

Method not found: 'Void SolrNet.Impl.SolrMoreLikeThisHandlerQueryResultsParser`1..ctor(SolrNet.Impl.ISolrAbstractResponseParser`1<System.__Canon>[])'.
