### ISSUE TITLE
Nuget package compiles to netcoreapp2.0 instead of netstandard2.0

### ISSUE THREAD

**Issue by omora-RA** [SolrNet/SolrNet#345]
The Nuget package:

[https://www.nuget.org/packages/SolrNetCore/](https://www.nuget.org/packages/SolrNetCore/)

Targets framework netcoreapp2.0.

I have a .netstandard2.0 class library and the command:

`dotnet publish`

Blows up with this error:

`error NU1202: Package SolrNetCore 1.0.0 is not compatible with netstandard2.0`

Shouldn't it target .netstandard2.0 instead?

**Comment by xavier-morera** [comment]
Which version of Visual Studio and Nuget are you using? Please see this: https://github.com/dotnet/core/issues/939

**Comment by xavier-morera** [comment]
Closing. Please reopen if you have further questions.
