### ISSUE TITLE
how to analysis Field Value in SolrNet SDK?

### ISSUE THREAD

**Issue by bidianqing** [SolrNet/SolrNet#346]
how to analysis Field Value in SolrNet SDK?

**Comment by xavier-morera** [comment]
Can you provide more information on this issue? I usually use Solr's administration tool for this purpose. What is your use case?

**Comment by bidianqing** [comment]
I want   get analysis Field Value result in SolrNet, How Do?

**Comment by xavier-morera** [comment]
Have you considered using the API directly? Please see this post

https://stackoverflow.com/questions/37783543/rest-api-for-solr-analyzer
