### ISSUE TITLE
Not compatible with latest version of Solr 7

### ISSUE THREAD

**Issue by vishal-dedania** [SolrNet/SolrNet#352]
SolrNet version is not compatible with latest version of solr 7. Most of the test cases are failing.

**Comment by gjunge** [comment]
@vishal-dedania  could you provide us with some more detail?

**Comment by vishal-dedania** [comment]
Just run the existing test suite with Solr version 7 to see all the errors.

**Comment by chandrabe** [comment]
@vishal-dedania  In Solr 7 the default output format for queries is switched from xml to json. 
Solrnet needs an xml output format.

In Solr, you can specify the output format at the query level with the wt parameter or apply it core wide with the queryResponseWriter clause in solrconfig.xml

Can you check you have configured Solr 7 with xml output format before running the tests ?

**Comment by gjunge** [comment]
@chandrabe @vishal-dedania 
This commit : https://github.com/SolrNet/SolrNet/commit/63842cf292b06d49b9c7303c8c6d9afa3d90e5b2 , which is already in our master branch, adds the `wt=xml` part 
So that should not be the issue.

**Comment by gjunge** [comment]
Also #368 adds `wt=xml` for the `SolrPostConnection` .

**Comment by vishal-dedania** [comment]
Thx
