### ISSUE TITLE
solr.EnumerateValidationResults() is not working with managed-schema

### ISSUE THREAD

**Issue by BkrBkr** [SolrNet/SolrNet#356]
Hello,

the function 'solr.EnumerateValidationResults()' is designed to work with the 'schema.xml' file only. May you add 'managed-schema' support aswell?

Thank You

**Comment by BkrBkr** [comment]
The attached patches should work with both: the schema.xml and the managed-schema file. BUT I didn't tested it with the schema.xml. For some unknown reason I can't debug the 'MappingValidator' so I didn't tested it either. But the results are looking good.

[Patch.zip](https://github.com/SolrNet/SolrNet/files/1582545/Patch.zip)

**Comment by gjunge** [comment]
@BkrBkr would you be able to create a Pull Request for this patch, it is just better documented if we do it the official way.

**Comment by BkrBkr** [comment]
Here you go: https://github.com/SolrNet/SolrNet/pull/357

**Comment by gjunge** [comment]
Thanks, I will have a look at it.

**Comment by gjunge** [comment]
Fixed by #357
