### ISSUE TITLE
How to use basic authentication when I want index data

### ISSUE THREAD

**Issue by ZivHsu** [SolrNet/SolrNet#359]
Hi All

this is my index code : 

 var solrFacility = new SolrNetFacility(SolrURL);
                    var container = new WindsorContainer();
                    container.AddFacility("solr", solrFacility);
                    var solr = container.Resolve<ISolrOperations<object>>();
                    try
                    {
                        solr.AddRange(DataList);
                        solr.Commit();
                    }

But now My Solr has been added basic authentication, so I need put the username and password,

so how to put the username and password in SolrNet?

**Comment by gjunge** [comment]
@ZivHsu  One of the classes set up by `SolrNetFacility` is `HttpWebRequestFactory` . This one has to be replaced in your DI by `BasicAuthHttpWebRequestFactory` see https://github.com/SolrNet/SolrNet/blob/master/SolrNet/HttpWebAdapters/Impl/BasicAuthHttpWebRequestFactory.cs .

**Comment by ZivHsu** [comment]
does it have sample code?
