### ISSUE TITLE
Fluent API for version 1.0.0

### ISSUE THREAD

**Issue by deepanshu203** [SolrNet/SolrNet#363]
Hi,

Is the Fluent API deprecated in version 1.0.0. SolrNet.DSL is not being found. 

Thanks,

**Comment by gjunge** [comment]
No it is not deprecated. Simply no nuspec package was created for the project. 
If you feel liking helping out, you can port it to a mixed net 4.6 / netstandard 2.0 package and add the correct nuspec file to the project. This way it will be automatically added to NuGet.

**Comment by gjunge** [comment]
I propose to rewrite the Fluent API as a set of extension methods, similar to how `Microsoft.Extensions.Logging` adds usefull methods to `ILogger`.

The current implementation is not useful for people that are using any other DI besides `CommonServiceLocator`.

Thoughts?

**Comment by Fatalityap** [comment]
Personally I don't want to use standard _ServiceLocator_, maybe someone can involve in this staff? )))

**Comment by mausch** [comment]
SolrNet.DSL was removed in c87fe4a5a7410d68707daea6ea0147ff62772ac3
Tbh it was never a good idea really.
