### ISSUE TITLE
Unity.SolrNetIntegration

### ISSUE THREAD

**Issue by JeroenvdBurg** [SolrNet/SolrNet#364]
Is it possible to upgrade the Unity version of Unity.SolrNetIntegration from 4.0 to 5.x?
the 4.0 version is deprecated and EOL.

thanks in advance. If you want I can try to create a pull request for it.

**Comment by xavier-morera** [comment]
Hello @JeroenvdBurg, help is deeply appreciated. It is great to have new contributors!  

I have created a branch for this work, please submit your pull request here:
https://github.com/SolrNet/SolrNet/tree/unity-5-upgrade

**Comment by JeroenvdBurg** [comment]
Hi Xavier, I finished the first upgrade to unity 5.0. 

Trying to push to the branch but I'm not allowed. Could you give me the permissions for the unity5 upgrade branch?

**Comment by gjunge** [comment]
@JeroenvdBurg  Hi Jeroen, 
Just push it to a local branch under a cloned version under your own github account, and then create a pull request to the https://github.com/SolrNet/SolrNet/tree/unity-5-upgrade branch.
If you need more help just let us know.

**Comment by JeroenvdBurg** [comment]
Thanks for your guidance. I have created the pull request.

**Comment by gjunge** [comment]
Thanks Jeroen, I will have a look at the PR tomorrow. 
Just FYI if you mention the issue number in the PR or in the commit message, like “fixes #364” GitHub will automatically link one to the other. I will do this by adding a comment to the PR, that will also work.
