### ISSUE TITLE
Does SolrNet support .net 4.0?

### ISSUE THREAD

**Issue by ZONGSS** [SolrNet/SolrNet#366]
Hello, I am a developer from China and are considering using your SolrNet. Some problems occurred during the experiment, and you need your help:

Is SolrNet supporting.net 4.0? I downloaded solrnet.core from NuGet and failed to install. 
Here's the tip: 
PM> Install-Package SolrNet.Core -Version 1.0.0
正在安装“SolrNet.Core 1.0.0”。
已成功安装“SolrNet.Core 1.0.0”。
正在将“SolrNet.Core 1.0.0”添加到 ConsoleApplication1。
正在卸载“SolrNet.Core 1.0.0”。
已成功卸载“SolrNet.Core 1.0.0”。
Install failed. Rolling back...
Install-Package : 无法安装程序包“SolrNet.Core 1.0.0”。您正在尝试将此程序包安装到某个将“.NETFramework,Version=v4.0”作为目标的项目中，但此程序包不包含与该框架兼容的任何程序集引用或内容文件。有关详细信息，请与程序包作者联系。
所在位置 行:1 字符: 16
+ Install-Package <<<<  SolrNet.Core -Version 1.0.0
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
PM> 

My VS is 2010, and the.net framework is 4.0. What's going on here?

Please be sure to reply. Thank you.（I can't communicate in English yet, so I'm using netease youdao. Please understand.）

**Comment by gjunge** [comment]
No, version 1.0.0 does not support .NET 4.0. 

However you can use older versions of SolrNet which include support for .NET 3.5, see https://www.nuget.org/packages/SolrNet/0.4.0.4001

**Comment by ZONGSS** [comment]
Ok, thank you very much.
