### ISSUE TITLE
.Net Core or Net Standard support for SolrNet.DSL

### ISSUE THREAD

**Issue by Fatalityap** [SolrNet/SolrNet#378]
Hi, I have downloaded SolrNet.DSL from nuget (https://www.nuget.org/packages/SolrNet.DSL/ ) But I see warning in my .net core 2.0 project:  _Package 'SolrNet.DSL 1.0.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project._ 

Any plans to add .net core support for this package?

**Comment by gjunge** [comment]
Please see #363 .

I propose to create a new fluent API project, being an 'extension method' only project, with only a dependency on SolrNet .Core  .

**Comment by Fatalityap** [comment]
Thanks
