### ISSUE TITLE
SolrNet.Microsoft.DependencyInjection example code

### ISSUE THREAD

**Issue by Fatalityap** [SolrNet/SolrNet#379]
Hi, I am a little bit struggling to find any example code that uses SolrNet.Microsoft.DependencyInjection, I am trying to do simple add to core, but as far as I see in fiddler it is causing strange behavior.

Can you give me some examples using SolrNet.Microsoft.DependencyInjection ?

**Comment by gjunge** [comment]
Once you set up as described here https://github.com/SolrNet/SolrNet/blob/master/Documentation/Initialization.md#microsoftextensionsdependencyinjection-aspnet-core

You should be able to get `ISolrOperations<YOURDOCUMENT>` via dependency injection.

With that interface you can do basically all Solr operations

For example:
``` csharp
await solr.DeleteAsync(SolrQuery.All);
await solr.AddAsync(p);
await solr.CommitAsync();
var products = await solr.QueryAsync(new SolrQueryByRange<decimal>("price", 10m, 100m));
`

**Comment by Fatalityap** [comment]
Thanks for answer. But when I will do this: 

`services.AddSolrNet("http://localhost:8983/solr"); ` Should I specify core directly into url or there is another way to do this?

**Comment by gjunge** [comment]
Yes, the core has to be specified directly.

Microsoft Dependency injection is a rather simple DI, for more advanced uses switch to any of the other DI engines.
