### ISSUE TITLE
Attempting to add duplicate SolrField should give a more helpful error

### ISSUE THREAD

**Issue by frjonsen** [SolrNet/SolrNet#380]
Obviously, attempting to use the same field-name in a single class, as in the code below, is an error, but it's not handled very gracefully.

Example:
```CSharp
class WithDuplicateFields
{
    [SolrField("foo")]
    public string Prop1 { get; set; }

    [SolrField("foo")]
    public string Prop2 { get; set; }
}
```

As it is, this will not be handled until AttributesMappingManager::GetFields is run, upon trying to add the document to an ISolrOperations-instance, where an exception will be thrown by the ToDictionary-call. In .NET Framework, the full error message given is `System.ArgumentException: 'An item with the same key has already been added.'`, which isn't very helpful at all. In .NET Core, the error message is `System.ArgumentException: 'An item with the same key has already been added. Key: foo'`, which is slightly better, but could probably be made more clear.

**Comment by gjunge** [comment]
@frjonsen Thanks for reporting the issue, you are right that the error message is not really friendly. Would you be interested in posting a fix?
