### ISSUE TITLE
Update example of cloud mode usage

### ISSUE THREAD

**Issue by Fatalityap** [SolrNet/SolrNet#384]
Hi, can you update example of cloud mode usage. ( https://github.com/SolrNet/SolrNet/blob/master/Documentation/Basic-usage-cloud.md ) ? 
It is not working for me. It seems that it is outdated. 

Also it will be nice that you can provide example of SolrNet Cloud Unity ))

**Comment by xavier-morera** [comment]
Hello @Fatalityap we are actually looking for someone to help us update SolrCloud documentation and test. Is this something that you believe you may be able to help?

**Comment by Fatalityap** [comment]
Hi @xavier-morera, thanks for great courses on Pluralsight. I will talk to my management but probably I can do it.

**Comment by Fatalityap** [comment]
I will write about decision of my management. Thanks for this opportunity! )

**Comment by xavier-morera** [comment]
Thanks @Fatalityap for your comment on the courses. I do what I can. Hope your management understands how they benefit as well from your gained experience by contributing to SolrNet and Solr

**Comment by Fatalityap** [comment]
Hi, sorry I am a little bit stuck, but maybe you know how to specify collection to write when I use Solr Net Cloud Unity. For example I want to write data only to **_new-collection_** collection.
Can you help me? )

**Comment by gjunge** [comment]
See #390 #

**Comment by dcpavelescu** [comment]
Is "Solrnet.Cloud" the dedicated API to be used when querying a collection in a solr cloud deployment? Or "Solrnet" API is the recommended API for querying operations also in case of a cloud deployment ?

Some observations (after looking into the code) to support the questions:
1.  Solrnet.Cloud API looks more like to focus on cluster status details and not on operating (e.g. query, update) the existing data.
2. However Solrnet.Cloud still provides some access to query operations through ISolrOperationsProvider, even if the GetOperations method is asking again for an URL (not clear what resource is referred by the url)... is ISolrOperationsProvider obsolete API? if not why is required to provide an URL at this stage?

**Comment by xmorera** [comment]
Solrnet can be used if you use a load balancer. SolrNet.Cloud is new-ish, so any testing and observations that you can provide can help improve it.

**Comment by dcpavelescu** [comment]
Could you please clarify which is the overall purpose of the Solrnet.Cloud library?
Does it plan to offer more control in comparison with Solrnet when interacting with a Cloud deployment?
Sorry if my question in case my questions look stupid, still hard to figure out scenarios where Solrnet.Cloud is the option of choice over Solrnet.

Thanks.
