### ISSUE TITLE
Example of using a custom IHttpWebRequestFactory with SolrNet.Core and SolrNet.Microsoft.DependencyInjection package

### ISSUE THREAD

**Issue by haggerty-william** [SolrNet/SolrNet#389]
I cant find out how to use SolrNet.Core and the SolrNet.Microsoft.DependencyInjection package together, can anyone point me in the right direction.
I thought that maybe adding a connection into the provider or adding the IHttpWebRequestFactory would do the trick but it didnt. I cant find any other way to add credentials either. Below is an example of what I was trying

```
SolrConnection connection = new SolrConnection(silrUrl);
connection.HttpWebRequestFactory = _httpWebRequestFactory;
IServiceProvider provider = new ServiceCollection().AddSingleton<ISolrConnection>(connection).AddSingleton<IHttpWebRequestFactory>(_httpWebRequestFactory).AddSolrNet(solrT).BuildServiceProvider();
ISolrOperations<EmptySolrResponse> solr = provider.GetRequiredService<ISolrOperations<EmptySolrResponse>>();
```

**Comment by gjunge** [comment]
See https://github.com/SolrNet/SolrNet/blob/master/Documentation/Initialization.md#microsoftextensionsdependencyinjection-aspnet-core

You have to register it using the `AddSolrNet` extension method: `services.AddSolrNet("http://localhost:8983/solr");`

After that you can get the service `ISolrOperations<EmptySolrResponse>` from the DI.

**Comment by haggerty-william** [comment]
I am doing exactly that in my example and the link provided does nothing more then I had already done in my example. So I will now assume that SolrNet.Microsoft.DependencyInjection is incompatible with solr servers that require authentication.

**Comment by dbeletsis** [comment]
That's exactly my problem: I can't find a way to use the above code to connect to a Solr Server that requires user credentials!

**Comment by dbeletsis** [comment]
I really don't understand, why such an important subject like Authentication isn't covered in the Documentation! Any help will be much appreciated!

**Comment by spal870** [comment]
Any update on this issue? I am facing issue to connect Solr server which need basic auth for Solrnet.core
