### ISSUE TITLE
Specifying collection in Solr Net Cloud Unity

### ISSUE THREAD

**Issue by Fatalityap** [SolrNet/SolrNet#390]
Hi, how can I specify collection to write and read when using Solr Net Cloud Unity integration. 

If I use following code it is writing to first created collection, witch is not stable for me. 

Here is a code:

```
    public class NumberPlate
    {
        [SolrField("id")]
        public string Id { get; set; }

        [SolrField("Number")]
        public string Number { get; set; }

        [SolrField("Organization")]
        public string Organization { get; set; }

        [SolrField("FirstName")]
        public string FirstName { get; set; }

        [SolrField("LastName")]
        public string LastName { get; set; }

        [SolrField("CountryOfRegistration")]
        public string CountryOfRegistration { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            MainAsync().Wait();
        }

        static async Task MainAsync()
        {
            //desktop-lmqi80k
            var provider = new SolrCloudStateProvider("desktop-lmqi80k:9983");
            await provider.InitAsync();
            var state = provider.GetCloudState();
            var colcount = state.Collections.Count;
            

            using (var container = new UnityContainer())
            {
                var cont = new Unity.SolrNetCloudIntegration.SolrNetContainerConfiguration().ConfigureContainer(provider, container);
                var obj = cont.Resolve<ISolrOperations<NumberPlate>>();

                obj.Add(new NumberPlate()
                {
                    CountryOfRegistration = "Ukraine",
                    FirstName = "Alexey",
                    LastName = "Ponomarenko",
                    Id = Guid.NewGuid().ToString(),
                    Number = "AA 6800 OB",
                    Organization = "KPI"
                });

                SolrQueryResults<NumberPlate> numberplates = obj.Query(new SolrQueryByField("CountryOfRegistration", "Ukraine"));
                Console.WriteLine("Product: " + numberplates.FirstOrDefault().Number);

                Console.WriteLine("Test");

                Console.ReadKey();
            }
        }
    }
```

Where can I specify collection to write and read (query)?

**Comment by Fatalityap** [comment]
Hi, for example in SolrJ here is this functionality https://lucene.apache.org/solr/7_1_0//solr-solrj/org/apache/solr/client/solrj/SolrClient.html#add-java.util.Collection- . You can specify collection in add method. How can I do it in Solr Net Cloud Unity?

**Comment by gjunge** [comment]
Disclaimer: My answer is purely theoretical from reading the source code, I've no experience with Solr Cloud nor Unity.

So I think it is rather simple:

``` csharp
 \\\ this calls the default collection
 var obj = cont.Resolve<ISolrOperations<NumberPlate>>();

 \\\ this way you are working with a specific collection
 var obj2 = cont.Resolve<ISolrOperations<NumberPlate>>("MYCOLLECTION");
```

Let me know if that works for you.

**Comment by Fatalityap** [comment]
Hi @gjunge . Thanks, it seems that it is working. At least I saw in Fiddler right collection.

**Comment by Fatalityap** [comment]
@gjunge  By the way, maybe you can give me some your contacts? For example skype/viber/whatsapp/telegram ? Maybe I can contact you if I will have some new questions?

**Comment by xavier-morera** [comment]
Hi @Fatalityap would it be possible to stick to using issues or StackOverflow instead of direct contact? Just for the following reasons:
1. This is volunteer work, so unless @gjunge or someone else wants to perform direct consulting which is 100%, I believe in respecting privacy and letting people help whenever they get a chance. People usually help when they get a chance
2. If @gjunge answers one of your questions here, the entire community benefits

Please both let me know if you are ok with my response. If @gjunge wants to help @Fatalityap directly is fine, but if you can share your knowledge with the rest of the community, it is way better.

Thoughts?

**Comment by gjunge** [comment]
Totally agree with @xavier-morera

**Comment by Fatalityap** [comment]
@xavier-morera  I hear you. Thanks for answer. I also agree with your point of view.
