### ISSUE TITLE
JSON Facet API 

### ISSUE THREAD

**Issue by alishawky** [SolrNet/SolrNet#418]
Hi Everyone 
To all SolrNet team you're doing great job

I've some issue of how to implement JSON Facet API in SolrNet
[JSON Facet API  ](http://yonik.com/solr-facet-functions/)

```
ISolrOperations<DeviceReadings> solr = connection.GetSolrInstance();
        QueryOptions queryOption = new QueryOptions
        {
            Rows = 0,
            FilterQueries = new ISolrQuery[] {
            new SolrQueryByField("playerId", query.PlayerId.ToString()),
            new SolrQueryByRange<DateTime>("dateTime", query.DateTimeFrom, query.DateTimeTo)
            },
            Facet = new FacetParameters
            {
                Queries = new List<ISolrFacetQuery>
                {
                    new SolrFacetFieldQuery("heartRate")
                }
            }

        };
        queryOption.ExtraParams = new KeyValuePair<string, string>[] {
            new KeyValuePair<string,string>("wt", "xml")
        };
        //Execute the query
        solrResults = solr.Query(SolrQuery.All, queryOption);
```

**Comment by gjunge** [comment]
Unfortunately currently SolrNet doesn't support the new JSON api's.

We do want to add this support, but we do not have a road map yet.

**Comment by sumit4bansal** [comment]
Any update on this?

**Comment by xmorera** [comment]
No work done yet @sumit4bansal. But if you contribute to this functionality, it could be released as part of SolrNet.

**Comment by Jay-Shete** [comment]
Any update on this in 2022?

**Comment by stephen-zhao** [comment]
I'm interested in adding JSON facet support to the library. Could we re-open this issue? @gjunge @xmorera -- tagging you both since you seem to have some ownership over this library (though that is not super clear, perhaps we could consider adding a CODEOWNERS file too). What are your thoughts?
