### ISSUE TITLE
Overriding the default mapper, built-in container example doesn't work

### ISSUE THREAD

**Issue by olegon** [SolrNet/SolrNet#423]
I'm using dotnet core and I've realized that [this example](https://github.com/SolrNet/SolrNet/blob/master/Documentation/Overriding-mapper.md#built-in-container) doesn't work.

I always get an container exception after putting this code in my application.

**Comment by xavier-morera** [comment]
Hello @olegon, would you be able to give it a shot and try to fix?

**Comment by olegon** [comment]
I'll send a pull request.
