### ISSUE TITLE
'Quoted' property in SolrQueryInList issue#185

### ISSUE THREAD

**Issue by stanuku** [SolrNet/SolrNet#428]
@mausch @xavier-morera  Do you plan to merge this PR? https://github.com/SolrNet/SolrNet/pull/185

**Comment by xavier-morera** [comment]
@gjunge what do you think?

**Comment by gjunge** [comment]
Seems like a good bug fix, I do not see any issues merging this.
Just have to bump the patch version after merge.

Do you want me to do it, or will you @xavier-morera ?

**Comment by xavier-morera** [comment]
I just merged @stanuku. 

@gjunge I will bump up version in a bit. Any other thing that you would like to include or want just this to go out?

**Comment by gjunge** [comment]
There is nothing else in the queue.

**Comment by xavier-morera** [comment]
I will bump and release later today then. Thank you.

**Comment by xavier-morera** [comment]
Ready: https://www.nuget.org/packages/SolrNet/1.0.10

Thanks @gjunge and @stanuku
