### ISSUE TITLE
Plain json object

### ISSUE THREAD

**Issue by meanin** [SolrNet/SolrNet#429]
Hi,
I am wondering if there are any options to not use strongly typed c# objects to work with ISolrOperation? How to add a document to the Solr instance without knowing its schema?
Best regards,
Paweł

**Comment by gjunge** [comment]
See https://github.com/SolrNet/SolrNet/blob/master/Documentation/Mapping.md#fully-loose-mapping

**Comment by meanin** [comment]
Yes, I saw that. How to configure IoC then? I am using autofac. Like below:
`
builder.RegisterModule(new SolrNetModule(new List<ISolrServer>
{
	new SolrServer("collectionname", "http://127.0.0.1:8983/solr/collectionname/", typeof(Dictionary<string,object>).AssemblyQualifiedName)
}));`

Then I am using interface `ISolrOperations<Dictionary<string, object>>` in my service implementation.
When I try to query all of the objects like 
`var solrQueryResults = await _solr.QueryAsync(SolrQuery.All);`

I am getting 404 and exception is thrown. How to get a proper data from Solr?

**Comment by meanin** [comment]
Ok, I found a bug in my thinking `"http://127.0.0.1:8983/solr/collectionname/"` has a redundant `/` at the end of the url. Maybe it is worth to consider using uri builder instead of concatenating strings to build query url?
