### ISSUE TITLE
Serialization of DateTime in local timezone

### ISSUE THREAD

**Issue by mr-KVA** [SolrNet/SolrNet#437]
Hello.

Implemented serialization ignores DateTimeKind.

https://github.com/SolrNet/SolrNet/blob/41296b6f67bfecbf182d76c4ae4996aa912cb3ee/SolrNet/Impl/FieldSerializers/DateTimeFieldSerializer.cs#L29

So if date value is in local timezone - it loose timezone.

however, seems that similar (DateTimeOffset)  serializer doesn't have this problem

https://github.com/SolrNet/SolrNet/blob/41296b6f67bfecbf182d76c4ae4996aa912cb3ee/SolrNet/Impl/FieldSerializers/DateTimeOffsetFieldSerializer.cs#L8

Would be ok to fix DateTimeFieldSerializer in the same way?

**Comment by xavier-morera** [comment]
Would you like to submit a pull request with the fix? Would be great to get a contribution.

**Comment by mr-KVA** [comment]
Pull request in here - https://github.com/SolrNet/SolrNet/pull/439

But I am not sure how to test it with UnitTest, cause framework uses machine timezone.
Open for any suggestion from your side.
Thanks.
