### ISSUE TITLE
Unable to Startup Solr Instance through .net Client for 4.6

### ISSUE THREAD

**Issue by akash3456** [SolrNet/SolrNet#440]
I am unable to startup the solr instance using the Startup.Init function as it does not exist anymore in the source code, is there another way to start up the instance using the solr.unity nuget package?

**Comment by gjunge** [comment]
Which NuGet packages are you using? It should be in the `SolrNet` package.

**Comment by kvrga-ecxio** [comment]
Hi @gjunge, I have the DLL referenced directly in my solution. After upgrading from 0.4.0 to 1.0.13, Startup.Init does not exist in SolrNet anymore (same problem as @akash3456). 
I even switched to the nuget package, but to no avail.
Any ideas?

**Comment by gjunge** [comment]
Youll need the SolrNet package, this includes solrnet core (which is just the lib without any DI container), and common service locator.

**Comment by NarayanaGara** [comment]
Same issue Startup class doesn't exists in SolrNet namespace in SolrNet.core  package in version 1.017.

**Comment by mausch** [comment]
Use the [sample app](https://github.com/SolrNet/SolrNetSampleApps) for reference on setting things up.
