### ISSUE TITLE
SolrConection not populating in ISolrOperation and receiving 401 in .net core 2.1 and 2.0 as well

### ISSUE THREAD

**Issue by amitsingh5290** [SolrNet/SolrNet#447]
Hi All,

I am facing issue of 401 in .net core 2.1 and 2.0 with Solr net with Microsoft DI. I am injecting  ISolrConnection and ISolrOperation in same class and I am seeing different connection for both object. ISolrConnection have default authrization header but the ISOLROperation didn't have that. Please below image of Isolroperation
![solr operation defaultrequest header blank](https://user-images.githubusercontent.com/43855309/46484228-f7618800-c816-11e8-9dac-23389470afd6.png)

See below header for I SolrConnection
![isolrconnection have default authrization header](https://user-images.githubusercontent.com/43855309/46484415-617a2d00-c817-11e8-9e4a-63cbbbb0259b.png)

I am initializationing  like below-:

> services.AddSolrNet<SolrContentItem>(solrConnectionConfiguration.SolrCoreUrl,options=> {options.HttpClient.DefaultRequestHeaders.Authorization = 
>                 new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(System.Text.Encoding.ASCII.GetBytes("userid:password")));});

Please suggest what i am doing wrong?

**Comment by gjunge** [comment]
I believe was had something fixed in the last version. Does this problem still occur?
