### ISSUE TITLE
Need support for .NET 4.5 VS2012 with Solr Cloud operations

### ISSUE THREAD

**Issue by techsupportsardonyx** [SolrNet/SolrNet#451]
With reference to the #450 

We are having the .NET project which is developed in 4.5 Framework (Visual Studio 2012) in that we need to implement the Solr with help of your SolrNet.

Which SolrNet version support the 4.5 Framework (Visual Studio 2012) with **Solr Cloud operations**?

**Comment by gjunge** [comment]
Solr Cloud is only available with 4.6 and up.
