### ISSUE TITLE
Get Solr quer URL

### ISSUE THREAD

**Issue by sumit4bansal** [SolrNet/SolrNet#464]
I need to log solr query url(including parameters), How can I get the URL which SolrNet is making request? URL comes as part of exception but not with results.

**Comment by sumit4bansal** [comment]
@gjunge Can you please look into above query

**Comment by xmorera** [comment]
You can use the LoggingConnection class

Something like this
```
var connection = new SolrConnection(solrURL);
var loggingConnection = new LoggingConnection(connection);
Startup.Init<Product>(loggingConnection);
```

See more in this link: https://github.com/SolrNet/SolrNetSampleApps/blob/master/SampleSolrApp/LoggingConnection.cs
