### ISSUE TITLE
Atomic update ignored due to wrong operation name

### ISSUE THREAD

**Issue by 1dot44mb** [SolrNet/SolrNet#474]
https://github.com/SolrNet/SolrNet/blob/818d843c74614ce0f202ad693baa5d08758beca3/SolrNet/Commands/AtomicUpdateCommand.cs#L80

`updateSpec.Type.ToString().ToLower()` translates "Inc" to "ınc" in Turkish locale which results in atomic update being ignored by Solr.
![image](https://user-images.githubusercontent.com/2939330/54282470-1d047180-45ad-11e9-86c4-254195dcc51f.png)

It should be `ToLowerInvariant()` to produce "inc" correctly in different locales.
Thanks.

**Comment by xmorera** [comment]
Hi @1dot44mb would you like to contribute this feature to SolrNet?

**Comment by 1dot44mb** [comment]
Hi @xmorera , Yes, i'm now working on it
