### ISSUE TITLE
SolrNet.Cloud with .NET Framework 4.5

### ISSUE THREAD

**Issue by erotokritosVall** [SolrNet/SolrNet#483]
Is there any way to use SolrNet.Cloud with a .NET Framework 4.5 version? If so, could you give some info about which version should I download etc? Thanks.

**Comment by gjunge** [comment]
@erotokritosVall  we don't have any version of SolrNet.Cloud that works on the older .NET frameworks. It is a relatively recent addition to SolrNet, so it was added as a .netstandard library.
