### ISSUE TITLE
Multiple Fully loose mapping with Default Startup Init

### ISSUE THREAD

**Issue by peppo1616** [SolrNet/SolrNet#485]
Is possibile manually define Key for during StartUp.Init() or there is a way to setup multiple loose core?

In particullary this case
var serverurl1 = "https://pathtosolr1"
var serverurl2 = "https://pathtosolr2"
Startup.Init<Dictionary<string, object>>(serverurl1,"key1");
Startup.Init<Dictionary<string, object>>(serverurl2,"key1");

var solr1 = ServiceLocator.Current.GetInstance<ISolrOperations<Dictionary<string, object>>>("key1");
var solr2 = ServiceLocator.Current.GetInstance<ISolrOperations<Dictionary<string, object>>>("key2");

**Comment by xmorera** [comment]
Hi, can you please look at this to see if it helps?

https://github.com/SolrNet/SolrNet/blob/master/Documentation/Multi-core-instance.md

**Comment by peppo1616** [comment]
Dim solrurl As String = ConfigurationManager.AppSettings("SolrServer1")
    Startup.Init(Of Dictionary(Of String, Object))(solrurl)

    Dim solrurl2 As String = ConfigurationManager.AppSettings("SolrServer2")
    Startup.Init(Of Dictionary(Of String, Object))(solrurl2)
This cause collision on key on with following error:

Key 'SolrNet.Impl.SolrConnection.System.Collections.Generic.Dictionary`2[System.String,System.Object].SolrNet.Impl.SolrConnection' already registered in container

This means that's no way to map same Dictionary<string, object> on differents cores ? There is any workaround?
