### ISSUE TITLE
Install SolrNet By Nuget

### ISSUE THREAD

**Issue by koramaz** [SolrNet/SolrNet#493]
Hello everyone,

Firstly, My english is not enough sorry. When I use the build and dll schemas look like pluralsight video's version 5.5, there is no problem, but when I try to install by nuget, I don't understand what to do. I've been looking for examples for days on google. but unfortunately I couldn't find anything. After downloading dll from nuget i want to open new core, But solr admin ui want the config file for the core. I couldn't find the default config to use as an example. How will this happen if I open a new core while use dll install Nuget package. I would appreciate your help.

Have a nice day

**Comment by xmorera** [comment]
Hello @koramaz 

Please take a look at this article in Microsoft Developer Network Magazine: https://msdn.microsoft.com/en-us/magazine/mt833410

It explains how to do the basic using the latest version of SolrNet
