### ISSUE TITLE
Failed parsing on POST method for SOLR

### ISSUE THREAD

**Issue by dsimoes** [SolrNet/SolrNet#505]
I'm using Sitecore (9.1) with SOLR (7.2.1) and when I configured Sitecore to use POST methods instead of GET I immediately get an exception on startup:

[XmlException: Data at the root level is invalid. Line 1, position 1.]
   System.Xml.XmlTextReaderImpl.Throw(Exception e) +91
   System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace() +408
   System.Xml.XmlTextReaderImpl.ParseDocumentContent() +487
   System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options) +60
   System.Xml.Linq.XDocument.Parse(String text, LoadOptions options) +156
   SolrNet.Impl.LowLevelSolrServer.SendAndParseHeader(ISolrCommand cmd) +40
   Sitecore.ContentSearch.SolrProvider.SolrNetIntegration.SolrPinger.Ping() +32
   Sitecore.ContentSearch.SolrProvider.SolrConnectors.SolrConnector.TestConnection() +70
   Sitecore.ContentSearch.SolrProvider.SolrStatus.OkSolrStatus() +99
   Sitecore.ContentSearch.SolrProvider.SolrStatus..cctor() +72

Logs from Jetty:

"POST https://localhost:8984/solr/admin/cores HTTP/1.1" 200 29533 

It seems that SolrNet is expecting to have XML on the response, but SOLR is returning JSON on the POST method, but I might be wrong.

Is this an issue with SolrNet or additional configuration must be performed on the Sitecore Solr Provider?

Thanks for the help.

**Comment by xmorera** [comment]
Older versions of Solr used XML as the default wt, but newer ones use JSON. You need to set it in the extraparams to JSON.

See this one https://github.com/SolrNet/SolrNet/issues/320
