### ISSUE TITLE
SpellCheck component not returning suggestions / collations on SolrNet

### ISSUE THREAD

**Issue by afk96** [SolrNet/SolrNet#507]
I am trying to implement solr  spellcheck on my asp.net mvc project . I have done the implementation on my project exactly like the one given in solrnet documentation and it does not return any count or result for suggestion/collation , although its perfectly returning me the results on Solr admin .

Solr version is solr 8.2.0 

Following is the code I am trying to run on my solrnet project .
` var r = solr.Query("knif", new QueryOptions
            {
                SpellCheck = new SpellCheckingParameters()
            });`

This is the results that gets no suggestions or collation when I run it .
![image](https://user-images.githubusercontent.com/55737812/68775535-777c3300-0650-11ea-96b9-429e94a62f96.png)

This is my request handler:
`<requestHandler name="/spell" class="solr.SearchHandler" startup="lazy">
    <lst name="defaults">
      <str name = "df">spellfield</str>
      <str name="spellcheck.dictionary">default</str>
      <str name="spellcheck.dictionary">wordbreak</str>
      <str name="spellcheck">on</str>
      <str name="spellcheckIndexDir">./spellchecker</str>
      <str name="spellcheck.count">10</str>
      <str name="spellcheck.alternativeTermCount">5</str>
      <str name="spellcheck.maxResultsForSuggest">5</str>
      <str name="spellcheck.collate">true</str>
      <str name="spellcheck.maxCollationTries">10</str>
      <str name="spellcheck.maxCollations">5</str> 
    </lst>
    <arr name="last-components">
      <str>spellcheck</str>
    </arr>
  </requestHandler>`

This is my search component:

'<searchComponent name="spellcheck" class="solr.SpellCheckComponent">

    <str name="queryAnalyzerFieldType">text_general</str>
    <lst name="spellchecker">
      <str name="name">default</str>
      <str name="field">spellfield</str>
      <str name="classname">solr.DirectSolrSpellChecker</str>
      
      <str name="distanceMeasure">internal</str>
      
      <float name="accuracy">0.5</float>
      
      <int name="maxEdits">2</int>
      
      <int name="minPrefix">1</int>
      
      <int name="maxInspections">5</int>
      
      <int name="minQueryLength">4</int>
      
      <float name="maxQueryFrequency">0.01</float>
    </lst>
    <lst name="spellchecker">
      <str name="name">wordbreak</str>
      <str name="classname">solr.WordBreakSolrSpellChecker</str>      
      <str name="field">spellfield</str>
      <str name="combineWords">true</str>
      <str name="breakWords">true</str>
      <int name="maxChanges">10</int>
    </lst>
  </searchComponent>`

This is the copyfield used for spellchecker :
`<copyField source="headnote" dest="spellfield"/>`
The headnote field has type=text_general .
I have tried almost everything but unable to get this working .

These are the results on solr admin in the picture attached :
![image](https://user-images.githubusercontent.com/55737812/68776321-b8287c00-0651-11ea-97f2-5fec6eddc0fc.png)

**Comment by afk96** [comment]
@gjunge @xmorera Can you look into this?

**Comment by gjunge** [comment]
@afk96 I currently don’t have access to a full Solr setup. I suggest forking the project, add a unit test and debug it in order to find the bug and create a PR.

**Comment by afk96** [comment]
@gjunge Thank you so much for your response . I'll try this and let you know . Appreciate your help . Keep up the good work .

**Comment by afk96** [comment]
@gjunge I found the problem in my solrconfig.xml file and found that I didn't passed the spellcheck component in my "/select" request handler . After passed it in my default handler I am now able to get the suggestions and collations as required . Thank you so much for your respone . :)
