### ISSUE TITLE
wt=xml is hardcoded in SolrConnection

### ISSUE THREAD

**Issue by LCHarold** [SolrNet/SolrNet#508]
For some context, we're using a middleware product in front of SOLR, and that product can only work with JSON responses from SOLR, not XML. I'm aware that the question of SolrNet supporting JSON responses has already been asked and the (quite reasonable) answer was that there isn't a compelling reason to support JSON in SolrNet.

However, because this middleware product only works with JSON, certain features in the product don't work unless it gets a JSON response from SOLR.

So, with that said, the issue I'm raising here is the fact that SolrConnection hardcodes `wt=xml`, which prevents setting `wt=json` on the request using `ExtraParams`.

I'll add that I've been successful in getting SolrNet to handle JSON responses by wiring up my own implementation of ISolrQueryExecuter, which parses the JSON response with Json.Net and then maps that into `SolrQueryResults` so everything else works normally. With the caveat that I'm only handling the parts of the response we're actually using, so it's by no means a complete implementation.

Resolving the hardcoding in SolrConnection would allow me to not have to use my hacked copy of SolrConnection.cs to get this all to work.

**Comment by xmorera** [comment]
Hello @LCHarold 

Would you like to provide a pull request that checks extra params for wt and can override wt=xml?

**Comment by LCHarold** [comment]
> Hello @LCHarold
> 
> Would you like to provide a pull request that checks extra params for wt and can override wt=xml?

See https://github.com/SolrNet/SolrNet/pull/509... it resolves the issue as far as I'm concerned.

**Comment by gjunge** [comment]
@LCHarold  thanks for the PR!

@xmorera , I've bumped the version and we can deploy the NuGet package.

**Comment by xmorera** [comment]
And I have published it thank you to both @LCHarold and @gjunge !
