### ISSUE TITLE
Is there a way to get a client instance without DI?

### ISSUE THREAD

**Issue by MartinKuhne** [SolrNet/SolrNet#513]
I'd like to switch the solr it is using on a per-request or per-controller basis. The model and core are the same.

Long version:
I am using a mock solr server to run itegration tests. This is so the query responses are deterministic and can be tested against. The mock solr server basically just returns preconfigured JSON files. To run the tests, I added a facility to tell my API to use a different solr server. However, it seesm the solr Uri can only be set at startup (we are using the MSFT asp.net core DI, so it needs that IServiceCollection to be present.

Do I have any options?

**Comment by gjunge** [comment]
Hi Martin,

Although it is certainly possible to use Solrnet without DI (or a simple DI), which you can see in our documentation, it is much simpler and better for you to use the .net DI version in your unit tests. 

It is rather simple, see this answer on StackOverflow: https://stackoverflow.com/questions/51180523/unit-testing-iservicecollection-registration

Basically create your ServiceCollection, add SolrNet, call create ServiceProvider and get the service. 

Hope that helps. 
Gidon

**Comment by MartinKuhne** [comment]
Thanks. I am allowing to change the Solr Uri on a per-call basis, so I didn't want to change global state. I'll try the approach you pointed out.
