### ISSUE TITLE
Solr - The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by TejendraPrasad** [SolrNet/SolrNet#518]
I have a standalone solr running on basic authentication and HTTPS.

With SolrNet - i am able to achieve basic authentication when running solr on HTTP but when i change to https it throws error - The request was aborted: Could not create SSL/TLS secure channel..

Below are the code snippet -please guide how to achieve both Basic Auth and SSL

//To create connection
`var solrConnection =
                        new SolrConnection(solrServerUrl.Trim())
                        {
                            HttpWebRequestFactory = new BasicAuthHttpWebRequestFactory(_solrUserName, _solrPassword),                            
                            ServerURL = solrServerUrl.Trim()
                        };`

//To check core staus

`ISolrCoreAdmin solrCoreAdmin = new SolrCoreAdmin(solrConnection, GetHeaderParser(), GetStatusResponseParser());
var solrCoreStatus = solrCoreAdmin.Status(_solrCoreName);`

`if (String.IsNullOrEmpty(solrCoreStatus.Name))
                {
                    var solrCoreCreate = solrCoreAdmin.Create(_solrCoreName, _solrInstanceDir);
                }`

When trying to execute the line `solrCoreAdmin.Status(_solrCoreName)` it throws SSL/TLS error.

Please guide me how to implement both HTTPS and Basic Authentication as i cannot find any example or document on how to achieve both.

Thank you!
Tej

**Comment by TejendraPrasad** [comment]
Hi,

Can anyone help me with above query it would be helpful.

Thank you!
Tej

**Comment by mausch** [comment]
Hi, have you seen this Stackoverflow question about it? https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel

In short, it usually means a problem with the version of SSL/TLS and you might have to force a particular version of TLS in your  app startup code before any SolrNet request.

**Comment by athir13en** [comment]
Hi, do you found any solution on this?
i'm facing same issue with solrNET 1.0.19.

My code as below, any guide to achieve connection to https?

`public IHttpWebRequest Create(Uri url)
        {
            var webrequest = (HttpWebRequest)WebRequest.Create(url);
            if (SettingsHelper.IsSolrAuthenticationEnabled())
            {
                webrequest.Credentials = new CredentialCache
                {
                    { url, "Basic", new NetworkCredential("username", "Password") }
                };
            }
            webrequest.Method = "POST";

            const SecurityProtocolType tls13 = (SecurityProtocolType)12288;

            ServicePointManager.Expect100Continue = true;            
            ServicePointManager.SecurityProtocol = tls13 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
            ServicePointManager.ServerCertificateValidationCallback = new System.Net.Security.RemoteCertificateValidationCallback(AcceptAllCertifications);

            webrequest.ContentType = "application/x-www-form-urlencoded";

            return new HttpWebRequestAdapter(webrequest);
        }`

**Comment by TejendraPrasad** [comment]
Hi,

Yes it worked for us.

It was Server issue, we have upgrade our sever to support TLS1.2 and it resolved.

So if its windows server, you need to update to support either TLS1.2 or TLS1.3 and in application use the same command at application startup.cs (.net)

ServicePointManager.Expect100Continue = true;            
        ServicePointManager.SecurityProtocol = tls13 |  SecurityProtocolType.Tls12;
        ServicePointManager.ServerCertificateValidationCallback = new System.Net.Security.RemoteCertificateValidationCallback(AcceptAllCertifications);

Even for me it was not working then after fixing the server it worked.

You can use IISCrypto to check version of TLS is enabled in your windows server.

thank you!
Tej
