### ISSUE TITLE
Solr Error: Not Found

### ISSUE THREAD

**Issue by Garwin4j** [SolrNet/SolrNet#521]
Hello, when I try connecting to a solr server, I get a not found error. I suspect that this is because I have not setup a core, but I thought that is what the Startup Command did:

```C#
Startup.Init<IndexObject>("https://localhost:port/solr");
```

So my question is, Do I need to create my core before trying to connect or should this command do all that for me?

**Comment by mausch** [comment]
Hi! `Startup.Init` only wires up the internal SolrNet components/config, it does not do anything to the actual Solr server.

**Comment by Garwin4j** [comment]
Okay... last question. Does:

```C#
ServiceCollection.AddSolrNet<Knowledge>("http://localhost:19883/solr/knowledge")
```
do the same thing as:

```C#
Startup.Init<IndexObject>("https://localhost:port/solr");
```

**Comment by mausch** [comment]
Yes, they both set up SolrNet. Difference is `Startup.Init` initialises things in the built-in / no-dependencies container, whereas `AddSolrNet` is for the Microsoft DI container (or SimpleInjector).
For reference check out https://github.com/SolrNet/SolrNet/blob/2ce1aa4fe7e8baf8a2025fde67371099fc32fbc8/Documentation/Initialization.md

**Comment by Garwin4j** [comment]
Thank you very much for you time and answers.
