### ISSUE TITLE
Dynamic Field Mapping suffix

### ISSUE THREAD

**Issue by ericcanadas** [SolrNet/SolrNet#526]
Hi, I have a Dynamic Field like this, with a suffix and not a prefix.

`<dynamicField name="*_fr" type="string" indexed="true" stored="true" multiValued="true"/>`

I see here the solution for dynamic Mapping : 
https://github.com/SolrNet/SolrNet/blob/master/Documentation/Mapping.md#dictionary-mappings-and-dynamic-fields

But this works with prefix but not with suffix ?

I try this but it's not working :
`[SolrField("*_fr")]`

Any solution ?

**Comment by mausch** [comment]
Hi Eric, unfortunately that's not implemented out of the box. You can see why here: https://github.com/SolrNet/SolrNet/blob/68cdbef08f7819b50b65b1f6548f8984feef51ff/SolrNet/Impl/DocumentPropertyVisitors/GenericDictionaryDocumentVisitor.cs#L83

You can do this by implementing your own ISolrDocumentPropertyVisitor and then replacing that in the container.
(for reference, the default implementation is https://github.com/SolrNet/SolrNet/blob/68cdbef08f7819b50b65b1f6548f8984feef51ff/SolrNet/Impl/DocumentPropertyVisitors/DefaultDocumentVisitor.cs )

**Comment by ericcanadas** [comment]
Ok thanks !!!
