### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by lixaotec** [SolrNet/SolrNet#529]
Dear fellows,

Just wondering if this tool is suitable for production uses?

It seems a little out-of-date, considering last release was 2019.

Or is it stable enough?

Thanks in advance

**Comment by mausch** [comment]
Hi, SolrNet is very stable by now. I think it addresses pretty much all the common features of Solr. To the best of my knowledge it's still the most feature-complete Solr client for .NET. 
Xavier and Gidon have been doing a great job maintaining the project.
If you have any technical questions feel free to open new issues!

Cheers

**Comment by xmorera** [comment]
As @mausch said, it is not abandoned but there are not many new features being added.  I use SolrNet in 2 of my company projects and it is stable as a rock.

@mausch created an amazing project @gjunge has done an amazing job on adding features and performing updates.

I have helped a bit on what I can, but I am totally overwhelmed on my day to day and night so I help in what I can.

**Comment by lixaotec** [comment]
Appreciate your response. That makes me more confident to use it on a project!

In fact it has been a challenge to choose techies now adays, so I have been very careful on picking tools and libs.

Im very grateful for your exp. sharing here. I´ve been looking for the most suitable FTS for my scenario, howerver wish to adopt something that will last a couple of years or more. Solr seem great alternative to Elasticsearch. FTS with faceted results with steady data (only incremental documents) seems more nicely payable with Solr until now. 

In this choose, im planning using Solr (instead of ElasticSearch) with .net, as my models are very strong, and .Net typing (and this SolrNet Tool) seems more suitable against nodejs for backend.

Would you recomend any additional info for me to dig on Solr .Net? Is this library similar to any on NodeJs?

**Comment by xmorera** [comment]
@lixaotec this is the last project that my company is currently working on: http://www.carroaunclick.com/

It is still WIP and this is just the "used car" part. The "new car configurator" is still undergoing design changes and the crawler with the "car appraisal and street value" part is about 70% done. 

I've been using SolrNet for multiple projects for about 6 years now and it works without issues.
