### ISSUE TITLE
AddSolrNet should be able to resolve URL from ServiceProvider.

### ISSUE THREAD

**Issue by bernarden** [SolrNet/SolrNet#530]
I'm using [options pattern](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options) with MS injection in my Asp.Net Core project. With the current implementation of AddSolrNet  and AddSolrNet<> methods I have to do the following:
```c#
services.Configure<SolrOptions>(Configuration.GetSection("Solr"));

var solrOptions = services.BuildServiceProvider().GetService<IOptions<SolrOptions>>().Value;
services.AddSolrNet<MyDto>($"{solrOptions.HostName}/solr/my-core");
```

IMO this is not ideal, since I have to unnecessarily build the service provider just to extract the host name. Alternately I could extract the value from the configuration object directly but then I'm losing the benefits of using the options pattern in the first place. I'm proposing to add an overload that instead of URL string takes a Func<IServiceProvider, string> that returns a URL. So the new usage would look like this:
```c#
services.Configure<SolrOptions>(Configuration.GetSection("Solr"));

services.AddSolrNet<MyDto>(sp => $"{sp.GetService<IOptions<SolrOptions>>().Value.HostName}/solr/my-core");
```

Note: `AddScoped`, `AddSingleton` and  `AddTransient ` have a similar overload, so this should be very familiar to developers who are using MS injection.

**Comment by gjunge** [comment]
Closed in https://github.com/SolrNet/SolrNet/commit/99bd68dbe1e2e632dc666722bcc884b01ad09335
