### ISSUE TITLE
ArgumentException when querying a results

### ISSUE THREAD

**Issue by shelland** [SolrNet/SolrNet#538]
Having a very simple search model:

```
public class ProductSearchModel
{
        [SolrUniqueKey("id")]
        public long Id { get; set; }

        [SolrField("name")]
        public string Name { get; set; }

        [SolrField("shortDescription")]
        public string ShortDescription { get; set; }

        [SolrField("description")]
        public string Description { get; set; }
}
```

It caused the following schema being created for all string fields:

![image](https://user-images.githubusercontent.com/426582/104414402-c732f300-55a2-11eb-97ad-04c7038b16cb.png)

Since all string fields are multivalued I can't make a query due to the type mismatching:

`var solrQuery = await this.solrOperations.QueryAsync("*:*");`

_**ArgumentException: Could not convert value 'System.Collections.ArrayList' to property 'Name' of document type ProductSearchModel.**_

Using the latest libraries from NuGet.

**Comment by mausch** [comment]
Hi, it seems you've already found the cause of your issue yourself :slightly_smiling_face: 
Just fix that type mismatch i.e. make your properties of type `IList<string>` and it should just work.
