### ISSUE TITLE
Phrase Query with slop

### ISSUE THREAD

**Issue by SirMrDexter** [SolrNet/SolrNet#540]
I have checked the documentations and code and could not figure out how to write a query like the one below using SolrNet.

`q=text:"digital group"~100`

Help please.

**Comment by mausch** [comment]
Hi, any of these should work:

`new SolrQuery("text:\"digital group\"~100")`
or
`new SolrQueryByField("text", "\"digital group\"~100") {Quoted = false}`

**Comment by SirMrDexter** [comment]
That's pretty much what I found as well. Was hoping may be there would be a separate property or query class which I could use instead as it could have been more elegant.

Had to do a small modification on top of your suggestion, in order to ensure the keywords are properly quoted.

`new SolrQueryByField("text", QueryByFieldSerializer.Quote(keyword) + "~100") {Quoted = false}`

Thanks for the help @mausch.
