### ISSUE TITLE
How to choose unified highlighter?

### ISSUE THREAD

**Issue by SirMrDexter** [SolrNet/SolrNet#542]
How can I choose unified highlighter when passing HighlighterParameter? From what I can see, there's no option for it. Is this a new feature which is yet to be implemented?

https://lucene.apache.org/solr/guide/6_6/highlighting.html#Highlighting-TheUnifiedHighlighter

**Comment by mausch** [comment]
Correct, `hl.method` is not currently implemented in https://github.com/SolrNet/SolrNet/blob/d868feab34272d4e50fe6b01bac4272fa265c82f/SolrNet/Commands/Parameters/HighlightingParameters.cs / https://github.com/SolrNet/SolrNet/blob/4cba32699d7b79f8e0d07065897c887456566d89/SolrNet/Impl/SolrQueryExecuter.cs#L298

**Comment by DnbChris** [comment]
Please implement the "hl.method" parameter in the HighlightingParameters. This is now urgently needed as in [Solr version 9.0](https://solr.apache.org/guide/solr/latest/upgrade-notes/major-changes-in-solr-9.html) there is a breaking change regarding the default Highlighter. 
("Highlighting: hl.method=unified is the new default. Use hl.method=original to switch back if needed.")

Are there other changes that are important for compatibility with Solr 9.0? I would appreciate if these changes would be implemented.
