### ISSUE TITLE
Map text_general field to string

### ISSUE THREAD

**Issue by Thaval** [SolrNet/SolrNet#556]
Hi,

is there a way to map text_general to a string instead of an array? I'm proving a Dictionary<string, object> as my data structure for SolrNet because I'll never know which fields are contained in Solr . However, I still need features that the standard solr.TextField does not provide, like highlighting and spell checks.
Iterating over the result and pulling out the value contained in the array affect performance too much, but of course, the result needs to be mapped somehow. 
Nevertheless, is there already a built-in solution to this?

**Comment by Thaval** [comment]
It's fine. Just set multiValued=false and you can map it to string.

**Comment by cupelapps** [comment]
Hi Thaval,
How did you achieve this? Can you elaborate?

Regards
Muthu

**Comment by Thaval** [comment]
I already answered this.
Just set multiValued=false for the field and it won't be an array of strings but a single string instead. Then it's normally mapped to a string without any further investigations.
