### ISSUE TITLE
Use without dependency injection container

### ISSUE THREAD

**Issue by Thaval** [SolrNet/SolrNet#569]
Hi,

is there an example on how to use this library without using any dependency injection container?

**Comment by mausch** [comment]
Depends on what you want to do exactly, but if you mean the usual operations you can start with:

```
ISolrOperations<MyDoc> solr = new SolrServer<MyDoc>(new SolrBasicServer<MyDoc>(...), ...)
```

and let the IDE/intellisense guide you to fill in `...` with the implementations of every interface/parameter passed to every object.

**Comment by mausch** [comment]
@Thaval ping, did that help? can we close this?

**Comment by Thaval** [comment]
Yea that helped and the issue can be closed, thanks.
