### ISSUE TITLE
SolrCloud with Microsoft Dependency Injection

### ISSUE THREAD

**Issue by Wintermute79** [SolrNet/SolrNet#582]
Is it possible to use SolrNet Cloud with ASP.NET Core built-in dependency injection?
There is no integration or example like for Unity or autofac, has anyone done this, yet?

**Comment by mausch** [comment]
There's no project for this at the moment. PRs welcome :slightly_smiling_face:

**Comment by mausch** [comment]
Duplicate of https://github.com/SolrNet/SolrNet/issues/381

**Comment by Wintermute79** [comment]
> There's no project for this at the moment. PRs welcome 🙂

Done in #585  🙂
