### ISSUE TITLE
Castle.Facilities.SolrNetIntegration: NugetPackage Broken and still at Version 1.0.0

### ISSUE THREAD

**Issue by groege** [SolrNet/SolrNet#587]
Hi,

There is something wrong with the nuget package.
First thing to notice is that the version number is not up to date with the SolrNet package.
The second but bigger problem ist that the nuget package is broken...
Trying to add it to a NetFramework 4.8 Project fails since it belives it is not compatible (SolrNet works just fine)...
So I created a NetStandard 2.0 Lib to put in between --> the install works, but no classes are being found.

Hope you can help :)
Cheers George

**Comment by mausch** [comment]
Not sure there's much I can do here except explain how this all  _should_ be working correctly :slightly_smiling_face: 

>  First thing to notice is that the version number is not up to date with the SolrNet package.

I'm not seeing this... back in Feb we had version [1.0.19 of SolrNet.Windsor](https://www.nuget.org/packages/SolrNet.Windsor/1.0.19), which defined `SolrNet.Core (>= 1.0.19)` as a dependency.

> Trying to add it to a NetFramework 4.8 Project fails since it belives it is not compatible (SolrNet works just fine)...
>  So I created a NetStandard 2.0 Lib to put in between --> the install works, but no classes are being found.

We publish all packages with targets .NETFramework 4.6 and .NETStandard 2.0. This should work for .NETFramework 4.8 as well without any issues.

Feel free to reopen if there are still issues around this.
