### ISSUE TITLE
Router.field bug

### ISSUE THREAD

**Issue by Jure-BB** [SolrNet/SolrNet#595]
Typo in "rooter.field". Should be "router.field".

https://github.com/SolrNet/SolrNet/blob/071d8b5fd5c53f4ddc7eec2a12aa26461e61e241/SolrNet.Cloud/CollectionsAdmin/SolrCollectionsAdmin.cs#L51

**Comment by mausch** [comment]
d'oh! Fixed now

**Comment by kostas-kelgeorgiadis** [comment]
If it is not much trouble, can someone describe what the effects of this bug could have been?
Because I get some random connection errors towards a Zookeeper enclave from times to times, and I can't figure out what is causing them. It may be happening when a ZK node goes offline, but I am not sure.
