### ISSUE TITLE
Using SolrNet.Cloud 1.1.1 in a .NET 8.0 project issues "Warning NETSDK1206"

### ISSUE THREAD

**Issue by poyyaren** [SolrNet/SolrNet#619]
When using SolrNet.Cloud 1.1.1 in a .NET 8.0 project it isssues warning NETSDK1206, because one of the dependencies uses a version-specific runtime-identifiere (RID).

"Starting with .NET 8, the default behavior of the .NET SDK and runtime is to only consider non-version-specific and non-distro-specific RIDs. When restoring and building, the SDK [uses a smaller portable RID graph](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph). The [RuntimeInformation.RuntimeIdentifier](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.runtimeidentifier#system-runtime-interopservices-runtimeinformation-runtimeidentifier) [returns the platform for which the runtime was built](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/runtimeidentifier). At run time, .NET finds [RID-specific assets using a known set of portable RIDs](https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/rid-asset-list). When building an application with RID-specific assets that may be ignored at runtime, the SDK will emit a warning: [NETSDK1206](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1206)." - source: [https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#using-rids](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#using-rids)

From the build output we can see, that the affected library is: Libuv

Warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): debian-x64, fedora-x64, opensuse-x64, rhel-x64, win7-arm, win7-x64, win7-x86. **Affected libraries: Libuv**. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.

**Comment by poyyaren** [comment]
Thank you for the fix @mausch. Any idea, when this will be released?

**Comment by inthegarden** [comment]
@mausch Is there a chance of this getting released? Many thanks!

**Comment by tYoshiyuki** [comment]
I hope this issue gets released.

**Comment by mausch** [comment]
I just pushed v1.1.2 to nuget

**Comment by inthegarden** [comment]
> I just pushed v1.1.2 to nuget

Thank you so much @mausch !!
