### ISSUE TITLE
What is the best way to integration test?

### ISSUE THREAD

**Issue by JROBOTO** [SolrNet/SolrNet#622]
I really like what you have done, it has made interacting with Solr from a C# app very easy. My only problem is I cannot effectively integration test. I am tentative to just mock out the ISolrQuery classes as a) I'd have to do that for each query type and b) I may misrepresent how this library functions thus making my test wrong. Is there a way I can mock out the actual data source and connect SolrNet to that data source?

I notice that instances of the client involve static registration of services, would this work across parallel tests?

**Comment by mausch** [comment]
For integration tests use https://dotnet.testcontainers.org/ .
See e.g. :
https://github.com/SolrNet/SolrNet/blob/6fea42493512c29b549a2c57a99fb52a3ebf6c34/SolrNet.Tests.Common/TestContainers.cs
https://github.com/SolrNet/SolrNetSampleApps/blob/e20f9525eeed94c94dc452c18f97f65a39aaf048/SampleSolrApp/Program.cs#L22
