### ISSUE TITLE
How can I find out when a collection was last modified?

### ISSUE THREAD

**Issue by JROBOTO** [SolrNet/SolrNet#624]
I need to know when a collection was last updated. Is this possible to do via SolrNet or at all outside of the web UI?

**Comment by mausch** [comment]
You're probably looking for this property: https://github.com/SolrNet/SolrNet/blob/87bbe48baaf8bd7ef5942ff4d164e4fecefd6afd/SolrNet/Impl/CoreIndexResult.cs#L53
