### ISSUE TITLE
LINQ provider

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#77]
(migrated from https://code.google.com/p/solrnet/issues/detail?id=18 )

See https://groups.google.com/d/msg/solrnet/YVCp4UN-J0U/6mrYBWII1csJ for reasons not to do this.

See https://github.com/mausch/SolrNet/tree/linq for some work in progress.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
