### ISSUE TITLE
Per-field highlighting parameters

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#78]
(migrated from https://code.google.com/p/solrnet/issues/detail?id=36 )

Add per-field highlighting parameters override. From http://wiki.apache.org/solr/HighlightingParameters :

Some parameters may be overriden on a per-field basis with the following 
syntax:

```
f.<fieldName>.<originalParam>=<value>
```

Test which parameters can be overriden.

Workaround: use ExtraParams. See http://teach-algo.blogspot.in/2013/05/solrnet-separate-highlighting-query-hlq.html

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
