### ISSUE TITLE
Function queries

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#79]
(moved from https://code.google.com/p/solrnet/issues/detail?id=58 )

Function queries can be used in SolrNet now, but only stringly-typed.
Model function queries ( http://wiki.apache.org/solr/FunctionQuery )

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
