### ISSUE TITLE
Nested queries

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#80]
(moved from https://code.google.com/p/solrnet/issues/detail?id=63 )

Figure out how to cleanly compose nested queries (see http://searchhub.org/2009/03/31/nested-queries-in-solr/ )

Workaround: compose them manually using LocalParams and query serializer.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
