### ISSUE TITLE
Multi-select facets

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#81]
(moved from https://code.google.com/p/solrnet/issues/detail?id=64 )

Figure out how to cleanly model [multi-select facets](http://wiki.apache.org/solr/SimpleFacetParameters#Multi-Select_Faceting_and_LocalParams) .

Multi-select facets can be readily used with SolrNet ([example](http://bugsquash.blogspot.com/2010/03/low-level-solrnet.html)) though a cleaner, simpler model would be useful.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
