### ISSUE TITLE
Connect to SolrIKVM

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#82]
(moved from https://code.google.com/p/solrnet/issues/detail?id=69 )

Implement a direct connection to [SolrIKVM](https://github.com/mausch/SolrIKVM), much like SolrJ has EmbeddedSolrServer.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
