### ISSUE TITLE
JavaBin

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#83]
(moved from https://code.google.com/p/solrnet/issues/detail?id=71 )

Support [JavaBin](https://svn.apache.org/repos/asf/lucene/dev/trunk/solr/solrj/src/java/org/apache/solr/common/util/JavaBinCodec.java).

Started in http://github.com/mausch/SolrNet/tree/javabin . However, the codec has a new version: http://wiki.apache.org/solr/javabin#Versions

See also https://groups.google.com/d/msg/solrnet/Bd1OW5YXsa0/R4KyZAtC3XkJ

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
