### ISSUE TITLE
Review Extract design

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#87]
(moved from https://code.google.com/p/solrnet/issues/detail?id=194 https://code.google.com/p/solrnet/issues/detail?id=79 )

The design of ExtractParams isn't completely consistent and needs some review. See https://groups.google.com/d/topic/solrnet/2_zwuMVQJ6o/discussion https://code.google.com/p/solrnet/issues/detail?id=79#c15

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
