### ISSUE TITLE
Support multi-core with built-in container

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#88]
(moved from https://code.google.com/p/solrnet/issues/detail?id=83 )

Enable multi-core support with same document type for the built-in container.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
