### ISSUE TITLE
Remove CommonServiceLocator

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#92]
(moved from https://code.google.com/p/solrnet/issues/detail?id=125 )

I only used it as a base to implement the built-in container, other than that it serves no real purpose. Ditch it.
Provide a separate package implementing a CommonServiceLocator adapter.

**Comment by AlexeyKozhemiakin** [comment]
Although there is no much practical difference between constructor and static method (just where to land a snippet of code) here are my thoughts in favor to static factory.

I'm not 100% confident in any of them yet(!), so please share what you think.

1. Startup class is definitely worth renaming to Solrnet at least. Startup makes no sense when reading code. Current Startup deserves [Obsolete] for sure :)
2. A use case of replacing a parser\serializer can be supported by (another) convenience method with serializer parameter. Or one can re-implement graph-creation method on it's own having in mind Startup example. btw we have a patch for CSV serializer which is generally 2 times less expensive compared to XML, it was critical for our app to upload dozens of items per minute.
3. And having all those convinience methods outside of SolrOperations implementation (separate business logic from infrastructure) seems reasonable.
4. In nearest future we will have several implementations of ISolrOperations - (names are not exact) SolrServer, LBSolrServer, CloudSolrServer, like in solrJ. I find it useful to have references to them in one static placeholder like an advertising of what we have. Not sure about it yet.

**Comment by sergey-tihon** [comment]
@mausch Do you agree to unlist from NuGet: `SolrNet.Autofac`, `SolrNet.Ninject`, `SolrNet.Unity`, `SolrNet.Windsor`, `SolrNet.StructureMap`, `SolrNet.CommonServices` and release single `SolrNet` package without DI?

**Comment by PeterSawyer** [comment]
Any chance we can fix this.  The dependency CommonServiceLocator (= 1.0.0) is most annoying.  I have gone back to 0.3.1 for the time being.

**Comment by jgreene** [comment]
+1 on CommonServiceLocator (= 1.0.0) being most annoying.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
