### ISSUE TITLE
Remove dependency on System.Web

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#93]
(moved from https://code.google.com/p/solrnet/issues/detail?id=140 , https://code.google.com/p/solrnet/issues/detail?id=134 )

Removing the dependency on System.Web would make SolrNet compatible with Xamarin.Android / iOS . See [report](http://scan.xamarin.com/Home/Report?scanId=fcbbcff4-b611-4e73-8134-01f7e1686562).

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
