### ISSUE TITLE
Remove ISolrCommand

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#94]
(moved from https://code.google.com/p/solrnet/issues/detail?id=147 )

ISolrCommand was not a good idea. It introduces an unnecesary abstraction that inverts control. Refactor to remove.

**Comment by AlexeyKozhemiakin** [comment]
@mausch could you please share your thoughts about this refactoring? Moving code from commands to solrserver will make the file heavy, isnt it?

**Comment by AlexeyKozhemiakin** [comment]
Sad thing that without intermediary ICommand it's impossible to unit-test parameter filling.

But frankly speaking usually it's quite straight forward and in most cases can be dropped.

@mausch please have a look at Collections API draft implementation https://gist.github.com/AlexeyKozhemiakin/a2770d502dd1b3c92643

It's using a minimalistic LowLevelSolr which can be shared with all other solr servers include CoreAdmin and simple solr.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
