### ISSUE TITLE
FastVectorHighlighter

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#95]
(moved from https://code.google.com/p/solrnet/issues/detail?id=149 )

Support FastVectorHighlighter and its options, see http://wiki.apache.org/solr/HighlightingParameters#hl.fragListBuilder

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
