### ISSUE TITLE
Load balancer

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#96]
(moved from https://code.google.com/p/solrnet/issues/detail?id=153 )

As described in http://wiki.apache.org/solr/LBHttpSolrServer . Make balancing algorithms pluggable, i.e. some implementations could be http://content.websitegear.com/article/load_balance_types.htm

Balancing algorithms should have access to response so that an impl can use qtime to schedule.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
