### ISSUE TITLE
ILookup mapping

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#98]
(moved from https://code.google.com/p/solrnet/issues/detail?id=156 )

Map ILookup by default to a dynamic multivalued field, using the name as a prefix just like with dictionary mapping.

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
