### ISSUE TITLE
Soft commits

### ISSUE THREAD

**Issue by mausch** [SolrNet/SolrNet#99]
(moved from https://code.google.com/p/solrnet/issues/detail?id=161 )

http://wiki.apache.org/solr/UpdateXmlMessages#A.22commit.22_and_.22optimize.22

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
